### ISSUE TITLE
noobaa_deploy_k8s.sh cannot set value for 'jwt' in noobaa-secrets

### ISSUE THREAD

**Issue by dongboyan77** [noobaa/noobaa-core#5680]
### Environment info
- NooBaa Version: **5.0.1**
- Platform: **OpenShift 3.11**

### Actual behavior
1.Use noobaa_deploy_k8s.sh to deploy noobaa on OpenShift, there is no value for 'jwt' in  noobaa-secrets. That causes noobaa pod cannot be ready.

### Expected behavior
1.NooBaa pod can be ready

### Steps to reproduce
1. $ ./noobaa_deploy_k8s.sh deploy -n noobaa

### More information - Screenshots / Logs / Other output
Aug-21 7:51:31.268 [/8868] [ERROR] CONSOLE:: PANIC: process uncaughtException Error: JWT_SECRET env variable not found. it must exist when running in kuberentes
    at get_jwt_secret (/root/node_modules/noobaa-core/src/server/common_services/auth_server.js:664:19)
    at Object.<anonymous> (/root/node_modules/noobaa-core/src/server/common_services/auth_server.js:22:20)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/root/node_modules/noobaa-core/src/server/object_services/map_server.js:17:21)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
2019-08-21 07:51:31,283 INFO exited: bg_workers (exit status 1; not expected)

**Comment by jeniawhite** [comment]
Hello,
Can you please write down the OpenSSL version that you are using?
Also, I would like to know if this command works in your environment: ```openssl rand -base64 20 | openssl sha512 -hmac | cut -c10-44```.
Thank you.

**Comment by dongboyan77** [comment]
`# openssl version
OpenSSL 1.1.0i-fips  14 Aug 2018
# openssl rand -base64 20 | openssl sha512 -hmac | cut -c10-44
sha512: Option -hmac needs a value
sha512: Use -help for summary.
140474359801664:error:02012020:system library:fflush:Broken pipe:crypto/bio/bss_file.c:320:fflush()
140474359801664:error:20074002:BIO routines:file_ctrl:system lib:crypto/bio/bss_file.c:322:`

**Comment by jeniawhite** [comment]
@dongboyan77 
I suggest using ```LibreSSL 2.6.5``` or similar version meanwhile since I know that it works with that.
Will issue a fix to support other versions of SSL as well.

**Comment by guymguym** [comment]
Actually openssl 1.0.2 works, but openssl 1.1.0 changed the sha512 -hmac usage.
But still each one of those behaves differently so this command is not stable between versions of openssl:
```
$ openssl version
LibreSSL 2.6.5
$ openssl rand -base64 20 | openssl sha512 -hmac
776021a6f3fc637f6f5b95a05d70d522dff14f56c9b0cc82e0f8bb9e01995172aa1cbdbe2f265de522b46daf3253440edc77d75628e637b4a7ab2cbbbc945496

$ /usr/local/Cellar/openssl/1.0.2s/bin/openssl rand -base64 20 | /usr/local/Cellar/openssl/1.0.2s/bin/openssl sha512 -hmac
(stdin)= 448db172816ee8633b648be18212d20c0b3eb22b84ecff62fc4c0c9620d1e44e3a7f95ada65a659f7119ebfa22dd25c8100e09554fbc993f1172acb1640e9827

$ /usr/local/opt/openssl@1.1/bin/openssl rand -base64 20 | /usr/local/opt/openssl@1.1/bin/openssl sha512 -hmac
sha512: Option -hmac needs a value
sha512: Use -help for summary.
```

**Comment by guymguym** [comment]
I think running hmac-sha512 on the random output is redundant for JWT secret generation.
@dongboyan77 You can change the script and replace this line with just:
```
openssl rand -hex 20
```
That would return 40 hex random characters (before we were cutting 35 characters from the sha512 output but that length doesn't make a difference to JWT).

**Comment by nimrod-becker** [comment]
@dongboyan77 You can take the new version of the script

**Comment by dongboyan77** [comment]
Thanks all, I will have a try
