### ISSUE TITLE
Support s3-compatible that fails with MalformedXML on deleteObjects()

### ISSUE THREAD

**Issue by guymguym** [noobaa/noobaa-core#5806]
### Environment info
- NooBaa Version: **5.2.2**
- Platform: **OpenShift 3?**
- User: @ron1

### Actual behavior
1. block_store_s3 calls s3.deleteObjects() to s3-compatible
2. This is the error in the logs:
```
[HostedAgents/36] [ERROR] [core.agent.block_store_services.block_store_s3:: _delete_blocks failed: { MalformedXML: The XML you provided was not well-formed or did not validate against our published schema
  at Request.extractError (/root/node_modules/noobaa-core/node_modules/aws-sdk/lib/services/s3.js:585:35)
  at Request.callListeners (/root/node_modules/noobaa-core/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
...
  at Request.transition (/root/node_modules/noobaa-core/node_modules/aws-sdk/lib/request.js:22:10)
...  
  at Request.<anonymous> (/root/node_modules/noobaa-core/node_modules/aws-sdk/lib/request.js:38:9) message: The XML you provided was not well-formed or did not validate against our published schema, code: MalformedXML, region: null, time: 2019-10-31T19:08:14.347Z, requestId: 12F455CC2337DE84, extendedRequestId: 13CDA3E36A783856, cfId: undefined, statusCode: 400, retryable: false, retryDelay: 35.80262916720886} { endpoint: https://my-s3-provider, endpoint_type S3_COMPATIBLE, target_bucket: test1, auth_method: AWS_V2, pool_name: test1-s3-srv }
[BGWorkers/31] [WARN] [core.server.object_services.map_deleter:: delete_blocks_from_node: node XXX n2n://YYY failed_block_ids 138
```

### Expected behavior
1. We should auto-detect the capabilities for each s3-compatible (in hosted agent init flow), and then keep that info in the block store to control if we can use signature v4/v2, x-amz-meta-*, and deleteObjects(multi).

### Steps to reproduce
1. NA

**Comment by jeniawhite** [comment]
Additional pointers:
- Remove the delegation configurations since the option got removed.
- Add lazy checks in the block store for supported MD information.
