### ISSUE TITLE
Question: Local Debugging

### ISSUE THREAD

**Issue by lallinger-arbeit** [noobaa/noobaa-core#6044]
I'd like to debug noobaa-core locally to support you with development, but i'm not able to get it started.

When i run npm run start the MongoDB and the services start. But it seems like the collections do not get initialized correctly (e.g. systems is empty and accounts only contains the Support account).
This results in the error message: 
`[Agent/4860] [ERROR] core.agent.agent_cli:: create_auth_token failed { RPC ERROR UNAUTHORIZED account not found
    at RpcRequest._set_response (/mnt/c/Users/lallin_p/Desktop/tmp/noobaa/noobaa-core/src/rpc/rpc_request.js:163:26)
    at RPC._on_response (/mnt/c/Users/lallin_p/Desktop/tmp/noobaa/noobaa-core/src/rpc/rpc.js:423:32)
    at RPC._on_message (/mnt/c/Users/lallin_p/Desktop/tmp/noobaa/noobaa-core/src/rpc/rpc.js:759:22)
    at RpcWsConnection.conn.on.msg (/mnt/c/Users/lallin_p/Desktop/tmp/noobaa/noobaa-core/src/rpc/rpc.js:594:40)
    at RpcWsConnection.emit (events.js:198:13)
    at RpcWsConnection.EventEmitter.emit (domain.js:448:20)
    at WebSocket.ws.on (/mnt/c/Users/lallin_p/Desktop/tmp/noobaa/noobaa-core/src/rpc/rpc_ws.js:44:53)
    at WebSocket.emit (events.js:198:13)
    at WebSocket.EventEmitter.emit (domain.js:448:20)
    at Receiver.receiverOnMessage (/mnt/c/Users/lallin_p/Desktop/tmp/noobaa/noobaa-core/node_modules/ws/lib/websocket.js:800:20)
    at Receiver.emit (events.js:198:13)
    at Receiver.EventEmitter.emit (domain.js:448:20)
    at Receiver.dataMessage (/mnt/c/Users/lallin_p/Desktop/tmp/noobaa/noobaa-core/node_modules/ws/lib/receiver.js:414:14)
    at Receiver.getData (/mnt/c/Users/lallin_p/Desktop/tmp/noobaa/noobaa-core/node_modules/ws/lib/receiver.js:353:17)
    at Receiver.startLoop (/mnt/c/Users/lallin_p/Desktop/tmp/noobaa/noobaa-core/node_modules/ws/lib/receiver.js:139:22)
    at Receiver._write (/mnt/c/Users/lallin_p/Desktop/tmp/noobaa/noobaa-core/node_modules/ws/lib/receiver.js:74:10)`

I'm not sure which environment variables i need to use to get it working. Could you please provide me with more information (https://github.com/noobaa/noobaa-core/wiki/Developers-Guide seems not to be up to date)? @guymguym or @jeniawhite ?

**Comment by Daornit** [comment]
any update on it

**Comment by guymguym** [comment]
Hey @lallinger-arbeit @Daornit 
You are right, our developer guide is poor.
Let me fix that ASAP and will ping you to give it a try.
And thank you for initiating this to shape up our developer experience :)

**Comment by guymguym** [comment]
Hey @lallinger-arbeit 

Yesterday on the community meeting ([doc](https://docs.google.com/document/d/1VgiNOuLW92KcuJ0sGnXRVfT9oeImwbzbpEb4QkCEvDY/edit?usp=sharing)) I updated that I started to work on organizing and merging noobaa docs to a single repo so that it will be easier to document all the pieces together rather than core vs operator separately.

So I created a new repo with github pages and started to edit the index and import docs, see here:
- https://github.com/noobaa/noobaa.github.io
- https://noobaa.github.io/

But this is still WIP...

**Comment by lallinger-arbeit** [comment]
Hey @guymguym 

Thanks for starting to work on this! I really like that you put all information together in a single repo!

I'm mostly interested in the [developers guide](https://github.com/noobaa/noobaa-core/wiki/Developers-Guide). Is this up to date or are there things missing? Last time i tried it seemed i'm missing some environment variables..

**Comment by lallinger-arbeit** [comment]
@liranmauda currently we do not need the possibility to debug locally, so i will close it, but you may reopen
