### ISSUE TITLE
noobaa-core pod fails to start with SystemStore: load failed Error: NON_EXISTING_ROOT_KEY

### ISSUE THREAD

**Issue by YiannisGkoufas** [noobaa/noobaa-core#6273]
### Environment info

INFO[0000] CLI version: 2.3.0                           
INFO[0000] noobaa-image: latest build from master  
INFO[0000] operator-image: noobaa/noobaa-operator:2.3.0 

- Platform: Kubernetes v1.17.12 | minikube  v1.14.2

### Actual behavior
Doesn't initialize with noobaa-core pod reporting:
```
Nov-20 10:00:01.422 [/15]    [L0] core.util.mongo_client:: connected
Nov-20 10:00:01.423 [/15] [ERROR] core.server.system_services.system_store:: SystemStore: load failed Error: NON_EXISTING_ROOT_KEY
    at MasterKeysManager.load_root_key (/root/node_modules/noobaa-core/src/server/system_services/master_key_manager.js:54:40)
    at /root/node_modules/noobaa-core/src/server/system_services/system_store.js:493:47
    at Semaphore.surround (/root/node_modules/noobaa-core/src/util/semaphore.js:40:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Nov-20 10:00:01.425 [/15] [ERROR] core.server.system_services.system_store:: SystemStore: load failed Error: NON_EXISTING_ROOT_KEY
    at MasterKeysManager.load_root_key (/root/node_modules/noobaa-core/src/server/system_services/master_key_manager.js:54:40)
    at /root/node_modules/noobaa-core/src/server/system_services/system_store.js:493:47
    at Semaphore.surround (/root/node_modules/noobaa-core/src/util/semaphore.js:40:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async init (/root/node_modules/noobaa-core/src/upgrade/upgrade_manager.js:44:9)
    at async run_upgrade (/root/node_modules/noobaa-core/src/upgrade/upgrade_manager.js:120:9)
    at async main (/root/node_modules/noobaa-core/src/upgrade/upgrade_manager.js:187:21)
Nov-20 10:00:01.515 [/15] [ERROR] UPGRADE:: failed to load system store!! Error: NON_EXISTING_ROOT_KEY
    at MasterKeysManager.load_root_key (/root/node_modules/noobaa-core/src/server/system_services/master_key_manager.js:54:40)
    at /root/node_modules/noobaa-core/src/server/system_services/system_store.js:493:47
    at Semaphore.surround (/root/node_modules/noobaa-core/src/util/semaphore.js:40:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async init (/root/node_modules/noobaa-core/src/upgrade/upgrade_manager.js:44:9)
    at async run_upgrade (/root/node_modules/noobaa-core/src/upgrade/upgrade_manager.js:120:9)
    at async main (/root/node_modules/noobaa-core/src/upgrade/upgrade_manager.js:187:21)
Nov-20 10:00:01.515 [/15] [ERROR] UPGRADE:: failed to init upgrade process!!
upgrade_manager failed with exit code 1
noobaa_init failed with exit code 1. aborting
```

### Steps to reproduce
1. `noobaa install --noobaa-image=<LATEST_IMAGE_BUILT_FROM_MASTER> --mini=true`

**Comment by guymguym** [comment]
@YiannisGkoufas the operator version should also be updated to latest image built from the operator repo master,
and then use the `--operator-image=<LATEST_OPERATOR_IMAGE>` flag to install.

**Comment by YiannisGkoufas** [comment]
makes sense! will try it asap

**Comment by YiannisGkoufas** [comment]
awesome @guymguym it worked, maybe we can have it somewhere in the instructions about the dev builds
