### ISSUE TITLE
Error: Invalid definition, hostname is mandatory

### ISSUE THREAD

**Issue by kanadaj** [noobaa/noobaa-core#6360]
### Environment info
- NooBaa Version: **5.6.0**
- Platform: **Kubernetes 1.20**

### Actual behavior
1. Installing with noobaa-operator, there seems to be an issue once noobaa is up; all GRPC requests seem to fail with the error `Error: Invalid definition, hostname is mandatory`.

### Expected behavior
1. Just... work?

### Steps to reproduce
1. Install noobaa on a brand new Kubernetes cluster installed with kubeadm and Calico
2. Wait for the operator to do its job

### More information - Screenshots / Logs / Other output

Using or not using Rook Ceph as the backing storage seems to make no difference.

Stacktraces:
```
[32mJan-20 22:31:03.308[35m [WebServer/35] [31m[ERROR][39m CONSOLE:: RPC._on_request: ERROR srv system_api.read_system reqid wss://noobaa-mgmt.rook-ceph.svc.cluster.local:443/rpc/-4499 connid ws://[::ffff:10.129.41.96]:52770/(3a3h2b5) Error: Invalid definition, hostname is mandatory
    at Object.construct_url (/root/node_modules/noobaa-core/src/util/url_utils.js:52:15)
    at /root/node_modules/noobaa-core/src/server/system_services/system_server.js:1249:35
    at Array.map (<anonymous>)
    at _list_s3_addresses (/root/node_modules/noobaa-core/src/server/system_services/system_server.js:1247:10)
    at /root/node_modules/noobaa-core/src/server/system_services/system_server.js:648:28
    at tryCatcher (/root/node_modules/noobaa-core/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/root/node_modules/noobaa-core/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/root/node_modules/noobaa-core/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/root/node_modules/noobaa-core/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/root/node_modules/noobaa-core/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/root/node_modules/noobaa-core/node_modules/bluebird/js/release/promise.js:673:18)
    at PropertiesPromiseArray.PromiseArray._resolve (/root/node_modules/noobaa-core/node_modules/bluebird/js/release/promise_array.js:127:19)
    at PropertiesPromiseArray._promiseFulfilled (/root/node_modules/noobaa-core/node_modules/bluebird/js/release/props.js:78:14)
    at Promise._settlePromise (/root/node_modules/noobaa-core/node_modules/bluebird/js/release/promise.js:609:26)
    at Promise._settlePromise0 (/root/node_modules/noobaa-core/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/root/node_modules/noobaa-core/node_modules/bluebird/js/release/promise.js:729:18)
```
    
```
    [32mJan-20 22:31:03.386[35m [WebServer/35] [33m [WARN][39m core.server.system_services.stats_aggregator:: Error in collecting partial systems stats, skipping current sampling point Error: Invalid definition, hostname is mandatory
    at construct_url (/root/node_modules/noobaa-core/src/util/url_utils.js:52:15)
    at Object.get_base_address (/root/node_modules/noobaa-core/src/util/addr_utils.js:40:20)
    at /root/node_modules/noobaa-core/src/server/system_services/stats_aggregator.js:378:88
[32mJan-20 22:31:03.386[35m [WebServer/35] [33m [WARN][39m core.server.system_services.stats_aggregator:: Error in collecting partial systems stats, skipping current stats collection Error: Invalid definition, hostname is mandatory
    at construct_url (/root/node_modules/noobaa-core/src/util/url_utils.js:52:15)
    at Object.get_base_address (/root/node_modules/noobaa-core/src/util/addr_utils.js:40:20)
    at /root/node_modules/noobaa-core/src/server/system_services/stats_aggregator.js:378:88 Error: Invalid definition, hostname is mandatory
    at construct_url (/root/node_modules/[4mnoobaa-core[24m/src/util/url_utils.js:52:15)
    at Object.get_base_address (/root/node_modules/[4mnoobaa-core[24m/src/util/addr_utils.js:40:20)
    at /root/node_modules/[4mnoobaa-core[24m/src/server/system_services/stats_aggregator.js:378:88
```

**Comment by kanadaj** [comment]
After some digging around, turns out it happened because I had a failed Openshift Router installation on vanilla k8s which triggered the additional logic for Route creation.
