### ISSUE TITLE
Error when accessing a file from cached namespace bucket

### ISSUE THREAD

**Issue by YiannisGkoufas** [noobaa/noobaa-core#6441]
### Environment info
- NooBaa Version: 5.6.0
- Platform: Kubernetes 1.18

### Actual behavior
1. Create cached namespace bucket
2. Able to list the files of the remote bucket
3. Not able to copy a file

### Expected behavior
1. Create cached namespace bucket
2. Able to list the files of the remote bucket
3. Able to copy a file

### More information - Screenshots / Logs / Other output

The main error reported on the endpoint pod is:
```
Apr-7 8:26:42.267 [Endpoint/14] [ERROR] core.rpc.rpc:: RPC._request: response ERROR srv object_api.update_endpoint_stats param
s { namespace_stats: [ { io_stats: { read_count: 607, write_count: 0, read_bytes: 554063233, write_bytes: 0, error_write_bytes: 0, error_write_count: 0, error_read_bytes: 0, error_read_count: 0 }, namespace_resource_id: '60658c3da2a804002ee6026b' }, [length]: 1 ], bucket_counters: [ { bucket_name: SENSITIVE-64a717a11f8d324e, content_type: 'binary/octet-stream', read_count: 700, write_count: 0 }, { bucket_name: SENSITIVE-64a717a11f8d324e, content_type: 'application/octet-stream', read_count: 4, write_count: 0 }, [length]: 2 ] } reqid 34499@fcall://fcall(7psnzeet) took [1.1+1.1=2.2] Error: not anonymous method update_endpoint_stats
```
Attaching more verbose logging as well

[noobaa.log](https://github.com/noobaa/noobaa-core/files/6273022/noobaa.log)

**Comment by guymguym** [comment]
Hey @YiannisGkoufas I think that these errors on update_endpoint_stats should not interrupt the S3 service.
Do you see that the read fails? Because I see in your log that it might have completed?

<details>
  <summary>Read request log</summary>

```
Apr-7 8:25:42.451 [Endpoint/14]    [L0] core.endpoint.s3.s3_rest:: S3 REQUEST
    GET /bucket1-cached/TPCDS-TEST-100G/call_center/part-00000-1f4a5e91-eac5-4190-8499-65d95212f848-c000.snappy.parquet 
    op get_object request_id kn76sf1t-8tcokv-gsr 
    { 
        host: 's3.noobaa.svc', 
        'accept-encoding': 'identity', 
        'user-agent': 'aws-cli/2.1.35 Python/3.8.8 Linux/4.15.0-140-generic exe/x86_64.debian.10 prompt/off command/s3.cp', 
        'x-amz-date': '20210407T082542Z', 
        'x-amz-content-sha256': 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', 
        authorization: 'AWS4-HMAC-SHA256 Credential=fOXTchSSFBmsUIHyLnY9/20210407/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=036b7375ceaef24cc0df8a646a456c4bb398398a16330e0623081582d260b3a6'
    }

Apr-7 8:25:42.452 [Endpoint/14]    [L0] core.server.object_services.object_server:: object_server.read_object_md: 
    { 
        bucket: SENSITIVE-64a717a11f8d324e,
        key: 'TPCDS-TEST-100G/call_center/part-00000-1f4a5e91-eac5-4190-8499-65d95212f848-c000.snappy.parquet'
    }

Apr-7 8:25:42.455 [Endpoint/14]    [L0] core.sdk.namespace_cache:: NamespaceCache.read_object_md use md from cache 
    { 
        obj_id: '606c85f72c09c0000e78e8fd',
        bucket: SENSITIVE-64a717a11f8d324e,
        key: 'TPCDS-TEST-100G/call_center/part-00000-1f4a5e91-eac5-4190-8499-65d95212f848-c000.snappy.parquet', 
        size: 13964, 
        etag: 'a2a7f60ad6165b1f9d621094c8ddd069', 
        md5_b64: 'oqf2CtYWWx+dYhCUyN3QaQ==', 
        content_type: 'binary/octet-stream', 
        create_time: 1617724919898, 
        last_modified_time: 1616334864000, 
        cache_last_valid_time: 1617783942436, 
        num_parts: 1, 
        is_latest: true, 
        xattr: { 'noobaa-namespace-s3-bucket': 'yiannis-tpcds-100' }, 
        stats: { reads: 0, last_read: 0 }, 
        tag_count: 0, 
        should_read_from_cache: true 
    }

Apr-7 8:25:42.456 [Endpoint/14]    [L0] core.sdk.namespace_cache:: NamespaceCache._read_object_stream 
    {
        params: { 
            object_md: { 
                obj_id: '606c85f72c09c0000e78e8fd', 
                bucket: SENSITIVE-64a717a11f8d324e, 
                key: 'TPCDS-TEST-100G/call_center/part-00000-1f4a5e91-eac5-4190-8499-65d95212f848-c000.snappy.parquet', 
                size: 13964, 
                etag: 'a2a7f60ad6165b1f9d621094c8ddd069', 
                md5_b64: 'oqf2CtYWWx+dYhCUyN3QaQ==', 
                content_type: 'binary/octet-stream', 
                create_time: 1617724919898, 
                last_modified_time: 1616334864000, 
                cache_last_valid_time: 1617783942436, 
                num_parts: 1, 
                is_latest: true, 
                xattr: { 'noobaa-namespace-s3-bucket': 'yiannis-tpcds-100' }, 
                stats: { reads: 0, last_read: 0 }, 
                tag_count: 0, 
                should_read_from_cache: true 
            }, 
            obj_id: '606c85f72c09c0000e78e8fd', 
            bucket: 'bucket1-cached', 
            key: 'TPCDS-TEST-100G/call_center/part-00000-1f4a5e91-eac5-4190-8499-65d95212f848-c000.snappy.parquet', 
            content_type: 'binary/octet-stream', 
            noobaa_trigger_agent: false, 
            md_conditions: undefined, 
            encryption: undefined, 
            read_size: 13964 
        }
    }

Apr-7 8:25:42.456 [Endpoint/14]    [L0] core.sdk.namespace_cache:: NamespaceCache: bucket usage 
    { 
        bucket_free_space_bytes: 3856416768, 
        bucket_usage: { 
            size: 15201595, 
            size_reduced: 516854505, 
            free: 4820520960, 
            available_for_upload: 4820520960, 
            last_update: 1617783828573 
        } 
    }

Apr-7 8:25:42.457 [Endpoint/14]    [L0] core.util.http_utils:: HTTP REPLY RAW 
    GET /bucket1-cached/TPCDS-TEST-100G/call_center/part-00000-1f4a5e91-eac5-4190-8499-65d95212f848-c000.snappy.parquet
```
</details>

**Comment by dannyzaken** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [https://github.com/noobaa/noobaa-core/issues/6441](https://trello.com/c/xs5I9kRo/6-https-githubcom-noobaa-noobaa-core-issues-6441)

**Comment by YiannisGkoufas** [comment]
Hi @guymguym yeah the file shows up but with 0 size

**Comment by YiannisGkoufas** [comment]
I noticed this error on the endpoint pod:
```
Apr-21 11:15:24.492 [Endpoint/11]    [L0] core.endpoint.s3.ops.s3_get_object:: request aborted: undefined
(node:11) UnhandledPromiseRejectionWarning: Error: Semaphore Timeout
    at Semaphore._on_timeout (/root/node_modules/noobaa-core/src/util/semaphore.js:215:25)
    at Timeout.<anonymous> (/root/node_modules/noobaa-core/src/util/semaphore.js:211:53)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(node:11) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 102)
(node:11) UnhandledPromiseRejectionWarning: Error: Semaphore Timeout
    at Semaphore._on_timeout (/root/node_modules/noobaa-core/src/util/semaphore.js:215:25)
    at Timeout.<anonymous> (/root/node_modules/noobaa-core/src/util/semaphore.js:211:53)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(node:11) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_
```

**Comment by guymguym** [comment]
@jeniawhite @dannyzaken @nimrod-becker Did you see issues with caching on 5.6?

@YiannisGkoufas What is your hub resource? AWS S3? S3 compatible? Also note that we recently released 5.7 perhaps you would prefer to use it on next runs. Another option is to use weekly master builds - @liranmauda do we have a wiki on weekly master builds so that it will be clear how to find the CLI, and the images etc... I see that @jeniawhite uploaded the last CLI to https://noobaa-operator-cli.s3.amazonaws.com/ but I wonder if the weekly build process pushed there too.

**Comment by nimrod-becker** [comment]
I believe we were not able to bring all the fixes of caching into 5.6, @YiannisGkoufas would it be possible for you to use the 5.7 version ? we have the images in the dockerhub repos

**Comment by YiannisGkoufas** [comment]
@guymguym @nimrod-becker It's IBM COS, I tried version 5.7 and builds from master with the same behaviour

**Comment by liranmauda** [comment]
>  @liranmauda do we have a wiki on weekly master builds so that it will be clear how to find the CLI, and the images etc... 

We Don't have a Wiki for that, AFAIK.

> I see that @jeniawhite uploaded the last CLI to https://noobaa-operator-cli.s3.amazonaws.com/ but I wonder if the weekly build process pushed there too.

The weekly build process should push `noobaa-operator-cli` unless something is not working.

**Comment by guymguym** [comment]
Created wiki for that - https://github.com/noobaa/noobaa-core/wiki/Weekly-Master-Builds

**Comment by guymguym** [comment]
@YiannisGkoufas Can you share the CR's - BackingStore, NamespaceStore, BucketClass?

**Comment by YiannisGkoufas** [comment]
Sure @guymguym, using the latest images+cli

https://github.com/noobaa/noobaa-operator/commit/bf95bd6e00a8a65e191915bc4b852761b005ad71
https://github.com/noobaa/noobaa-core/commit/4ce639a13908fa898bb31be8d44aac3b97ebd512

I am not able to do even an `ls` 
```
[yiannis@oc3656886087 ~]$ aws s3 --endpoint-url=https://150.238.203.59:443 --no-verify-ssl ls
/usr/local/aws-cli/v2/2.1.3/dist/urllib3/connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host '150.238.203.59'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings

expected string or bytes-like object
```
From the CRDs you suggested I only had a backinstore and a bucket class (added the connection and the namespace bucket via the UI)

[noobaa_crds.zip](https://github.com/noobaa/noobaa-core/files/6357999/noobaa_crds.zip)

**Comment by YiannisGkoufas** [comment]
Another observation from @pkoutsov, when starting up all the components outside of the k8s environment we don't get this behaviour.
