### ISSUE TITLE
Standalone NSFS read_rand_seed: error TypeError: fh.read is not a function

### ISSUE THREAD

**Issue by guymguym** [noobaa/noobaa-core#6476]
### Environment info
- NooBaa Version: **master-20210427**
- Platform: **Standalone**

### Actual behavior
1. 
```
$ brew reinstall noobaa-core
...
$ noobaa-core nsfs .
Apr-27 10:59:10.985 [Endpoint/86589]    [L0] core.rpc.rpc:: RPC register_n2n_proxy
Apr-27 10:59:11.271 [Endpoint/86589]    [L0] core.endpoint.endpoint:: Configured Virtual Hosts: []
Apr-27 10:59:11.271 [Endpoint/86589]    [L0] core.endpoint.endpoint:: Configured Location Info: { region: '' }
Apr-27 10:59:11.272 [Endpoint/86589]   [LOG] CONSOLE:: read_rand_seed: reading 32 bytes from /dev/random ...
Apr-27 10:59:11.273 [Endpoint/86589]   [LOG] CONSOLE:: read_rand_seed: error TypeError: fh.read is not a function
    at read_rand_seed (/snapshot/noobaa-core-20210427-80602-1didalo/src/util/nb_native.js:86:44)
    at async init_rand_seed (/snapshot/noobaa-core-20210427-80602-1didalo/src/util/nb_native.js:51:18)
Apr-27 10:59:11.273 [Endpoint/86589]   [LOG] CONSOLE:: read_rand_seed: closing fd ...
Apr-27 10:59:11.273 [Endpoint/86589]   [LOG] CONSOLE:: read_rand_seed: closing fd error TypeError: fh.close is not a function
    at clean_fh (/snapshot/noobaa-core-20210427-80602-1didalo/src/util/nb_native.js:69:22)
    at read_rand_seed (/snapshot/noobaa-core-20210427-80602-1didalo/src/util/nb_native.js:91:19)
    at async init_rand_seed (/snapshot/noobaa-core-20210427-80602-1didalo/src/util/nb_native.js:51:18)
Apr-27 10:59:11.273 [Endpoint/86589]   [LOG] CONSOLE:: read_rand_seed: delay before retry
```

### Expected behavior
1. Should not fail - not sure why this fs/promises open file handle flow is different after using pkg.

### Steps to reproduce
1. see above.

**Comment by guymguym** [comment]
https://github.com/vercel/pkg/issues/1162

**Comment by guymguym** [comment]
@jeniawhite Until the issue from pkg is resolved, perhaps we can just identify that `await fs.promises.open()` returns a number (fd) instead of object and return from the read_rand_seed function? this will avoid making redundant changes to our code and just wait until the issue is resolved by skipping the random see for standalone.
https://github.com/noobaa/noobaa-core/blob/efe45cfffee2cc4b0b24671743013b5ddc5cca43/src/util/nb_native.js#L83
