### ISSUE TITLE
Noobaa db pod crashed in system idle state

### ISSUE THREAD

**Issue by akmithal** [noobaa/noobaa-core#6550]
### Environment info
- NooBaa Version: Defined below as were using custom image and upstream code together
- Platform: OCP 4.6.16

[root@ocp-akshat-1-inf ~]# for i in noobaa-core-0 noobaa-db-0 noobaa-endpoint-5d874b858b-gqh9f noobaa-operator-7c9c876b8c-jmxf5 ; do echo "pod $i"; oc describe pod $i |grep "Image:"; done
pod noobaa-core-0
    Image:          jeniawhite/noobaa-core:debugakshat
pod noobaa-db-0
    Image:         jeniawhite/noobaa-core:debugakshat
    Image:         centos/mongodb-36-centos7
pod noobaa-endpoint-5d874b858b-gqh9f
    Image:         jeniawhite/noobaa-core:debugakshat
pod noobaa-operator-7c9c876b8c-jmxf5
    Image:          noobaa/noobaa-operator:master-20210531

### Actual behavior
1. Did Noobaa db pod should not crash. 

### Expected behavior
1. The noobaa db and endpoint pods should not crash 

### Steps to reproduce
1. System is idle when this crash happened

```
[root@ocp-akshat-1-inf ~]# podn
NAME                               READY   STATUS             RESTARTS   AGE
noobaa-core-0                      1/1     Running            0          19h
noobaa-db-0                        0/1     CrashLoopBackOff   78         19h
noobaa-endpoint-5d874b858b-gqh9f   0/1     Error              57         19h
noobaa-operator-7c9c876b8c-jmxf5   1/1     Running            0          19h
```

### More information - Screenshots / Logs / Other output

Endpoint crash logs:
```

Jun-4 5:02:30.699 [Endpoint/8] [ERROR] core.util.mongo_client:: _connect: initial connect failed, will retry MongoNetworkError: failed to connect to server [noobaa-db-0.noobaa-db:27017] on first connect [Error: getaddrinfo ENOTFOUND noobaa-db-0.noobaa-db
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26) {
  name: 'MongoNetworkError'
}]
    at Pool.<anonymous> (/root/node_modules/noobaa-core/node_modules/mongodb/lib/core/topologies/server.js:438:11)
    at Pool.emit (events.js:315:20)
    at Pool.EventEmitter.emit (domain.js:467:12)
    at /root/node_modules/noobaa-core/node_modules/mongodb/lib/core/connection/pool.js:562:14
    at /root/node_modules/noobaa-core/node_modules/mongodb/lib/core/connection/pool.js:995:11
    at /root/node_modules/noobaa-core/node_modules/mongodb/lib/core/connection/connect.js:32:7
    at callback (/root/node_modules/noobaa-core/node_modules/mongodb/lib/core/connection/connect.js:280:5)
    at Socket.<anonymous> (/root/node_modules/noobaa-core/node_modules/mongodb/lib/core/connection/connect.js:310:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
Jun-4 5:02:33.700 [Endpoint/8]    [L0] core.util.mongo_client:: _connect: called with mongodb://noobaa-db-0.noobaa-db/nbcore
Jun-4 5:02:35.780 [Endpoint/8] [ERROR] core.util.mongo_client:: _connect: initial connect failed, will retry MongoNetworkError: failed to connect to server [noobaa-db-0.noobaa-db:27017] on first connect [Error: getaddrinfo ENOTFOUND noobaa-db-0.noobaa-db
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26) {
  name: 'MongoNetworkError'
}]
    at Pool.<anonymous> (/root/node_modules/noobaa-core/node_modules/mongodb/lib/core/topologies/server.js:438:11)
    at Pool.emit (events.js:315:20)
    at Pool.EventEmitter.emit (domain.js:467:12)
    at /root/node_modules/noobaa-core/node_modules/mongodb/lib/core/connection/pool.js:562:14
    at /root/node_modules/noobaa-core/node_modules/mongodb/lib/core/connection/pool.js:995:11
    at /root/node_modules/noobaa-core/node_modules/mongodb/lib/core/connection/connect.js:32:7
    at callback (/root/node_modules/noobaa-core/node_modules/mongodb/lib/core/connection/connect.js:280:5)
    at Socket.<anonymous> (/root/node_modules/noobaa-core/node_modules/mongodb/lib/core/connection/connect.js:310:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
Jun-4 5:02:38.343 [Endpoint/8] [ERROR] core.util.mongo_client:: Connection closed for more  300000 , quitting




######################################################################
Fri Jun  4 05:02:38 UTC 2021 NooBaa: Process exited RIP (RC=1)
######################################################################
```

Noobaa-db-0 pod logs:
```

[root@ocp-akshat-1-inf ~]# oc logs noobaa-db-0    
2021-06-04T04:55:52.845+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/mongo/cluster/shard1 64-bit host=noobaa-db-0
2021-06-04T04:55:52.845+0000 I CONTROL  [initandlisten] db version v3.6.3
2021-06-04T04:55:52.845+0000 I CONTROL  [initandlisten] git version: nogitversion
2021-06-04T04:55:52.845+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.2k-fips  26 Jan 2017
2021-06-04T04:55:52.845+0000 I CONTROL  [initandlisten] allocator: tcmalloc
2021-06-04T04:55:52.845+0000 I CONTROL  [initandlisten] modules: none
2021-06-04T04:55:52.845+0000 I CONTROL  [initandlisten] build environment:
2021-06-04T04:55:52.845+0000 I CONTROL  [initandlisten]     distarch: x86_64
2021-06-04T04:55:52.845+0000 I CONTROL  [initandlisten]     target_arch: x86_64
2021-06-04T04:55:52.845+0000 I CONTROL  [initandlisten] options: { net: { bindIpAll: true, port: 27017 }, storage: { dbPath: "/data/mongo/cluster/shard1" } }
2021-06-04T04:55:52.845+0000 W -        [initandlisten] Detected unclean shutdown - /data/mongo/cluster/shard1/mongod.lock is not empty.
2021-06-04T04:55:52.846+0000 I -        [initandlisten] Detected data files in /data/mongo/cluster/shard1 created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
2021-06-04T04:55:52.846+0000 W STORAGE  [initandlisten] Recovering data from the last clean checkpoint.
2021-06-04T04:55:52.847+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=15567M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
2021-06-04T04:55:53.743+0000 I STORAGE  [initandlisten] WiredTiger message [1622782553:743025][1:0x7f1807667b80], txn-recover: Main recovery loop: starting at 77/256
2021-06-04T04:55:53.743+0000 I STORAGE  [initandlisten] WiredTiger message [1622782553:743667][1:0x7f1807667b80], txn-recover: Recovering log 77 through 78
2021-06-04T04:55:53.791+0000 I STORAGE  [initandlisten] WiredTiger message [1622782553:791567][1:0x7f1807667b80], txn-recover: Recovering log 78 through 78
2021-06-04T04:55:53.875+0000 E STORAGE  [initandlisten] WiredTiger error (5) [1622782553:875128][1:0x7f1807667b80], file:_mdb_catalog.wt, WT_SESSION.open_cursor: /data/mongo/cluster/shard1/_mdb_catalog.wt: handle-read: pread: failed to read 4096 bytes at offset 0: Input/output error
2021-06-04T04:55:53.875+0000 F -        [initandlisten] Invariant failure: ret resulted in status UnknownError: 5: Input/output error at src/mongo/db/storage/wiredtiger/wiredtiger_session_cache.cpp 97
2021-06-04T04:55:53.875+0000 F -        [initandlisten] 

***aborting after invariant() failure


2021-06-04T04:55:53.875+0000 F -        [initandlisten] Got signal: 6 (Aborted).

 0x555ccafeef1a 0x555ccafee27e 0x555ccafee752 0x7f1804338630 0x7f1803f91387 0x7f1803f92a78 0x555cc9789261 0x555cc985212d 0x555cc9851969 0x555cc9847368 0x555cc9847416 0x555cc984cd31 0x555cc9836cbd 0x555cc99a8912 0x555cc981fd2d 0x555cc9a245d3 0x555cc97fbc29 0x555cc97fef56 0x555cc978ac89 0x7f1803f7d555 0x555cc97eae45
----- BEGIN BACKTRACE -----
{"backtrace":[{"b":"555CC94DC000","o":"1B12F1A"},{"b":"555CC94DC000","o":"1B1227E"},{"b":"555CC94DC000","o":"1B12752"},{"b":"7F1804329000","o":"F630"},{"b":"7F1803F5B000","o":"36387","s":"gsignal"},{"b":"7F1803F5B000","o":"37A78","s":"abort"},{"b":"555CC94DC000","o":"2AD261"},{"b":"555CC94DC000","o":"37612D"},{"b":"555CC94DC000","o":"375969"},{"b":"555CC94DC000","o":"36B368"},{"b":"555CC94DC000","o":"36B416"},{"b":"555CC94DC000","o":"370D31"},{"b":"555CC94DC000","o":"35ACBD"},{"b":"555CC94DC000","o":"4CC912"},{"b":"555CC94DC000","o":"343D2D"},{"b":"555CC94DC000","o":"5485D3"},{"b":"555CC94DC000","o":"31FC29"},{"b":"555CC94DC000","o":"322F56"},{"b":"555CC94DC000","o":"2AEC89"},{"b":"7F1803F5B000","o":"22555","s":"__libc_start_main"},{"b":"555CC94DC000","o":"30EE45"}],"processInfo":{ "mongodbVersion" : "3.6.3", "gitVersion" : "nogitversion", "compiledModules" : [], "uname" : { "sysname" : "Linux", "release" : "4.18.0-193.41.1.el8_2.x86_64", "version" : "#1 SMP Wed Jan 13 11:33:33 EST 2021", "machine" : "x86_64" }, "somap" : [ { "b" : "555CC94DC000", "elfType" : 3, "buildId" : "994546E1D7E0DB84D44F8FFCE44321A3F942C8B6" }, { "b" : "7FFCD57B8000", "elfType" : 3, "buildId" : "3BC88DB79572218D35DE971FDCE79180D65FDCD2" }, { "b" : "7F1807207000", "path" : "/opt/rh/rh-mongodb36/root/usr/lib64/libstemmer.so.rh-mongodb36-0", "elfType" : 3, "buildId" : "95E1975085E3E88948957C518EC54CF19A180AF8" }, { "b" : "7F1806FF1000", "path" : "/lib64/libz.so.1", "elfType" : 3, "buildId" : "B9D5F73428BD6AD68C96986B57BEA3B7CEDB9745" }, { "b" : "7F1806DEB000", "path" : "/lib64/libsnappy.so.1", "elfType" : 3, "buildId" : "3CEB901120465B031FA92FA449A9AD981CEC1659" }, { "b" : "7F1806B65000", "path" : "/opt/rh/rh-mongodb36/root/usr/lib64/libyaml-cpp.so.rh-mongodb36-0.5", "elfType" : 3, "buildId" : "6F5B95F01DE486B0DD06C8281E3BD6443A4006EC" }, { "b" : "7F1806903000", "path" : "/lib64/libpcre.so.1", "elfType" : 3, "buildId" : "9CA3D11F018BEEB719CDB34BE800BF1641350D0A" }, { "b" : "7F18066FA000", "path" : "/lib64/libpcrecpp.so.0", "elfType" : 3, "buildId" : "8BBAA8A5638DCB0C4B523FCA4B54613AE543BDF1" }, { "b" : "7F1806487000", "path" : "/opt/rh/rh-mongodb36/root/usr/lib64/libboost_program_options.so.rh-mongodb36-1.60.0", "elfType" : 3, "buildId" : "FEEEC1BDA6987D52F313877C6C4F216E4967C751" }, { "b" : "7F1806270000", "path" : "/opt/rh/rh-mongodb36/root/usr/lib64/libboost_filesystem.so.rh-mongodb36-1.60.0", "elfType" : 3, "buildId" : "42F19F782EF63CE1C7FEEEA0FF8A34129359AE14" }, { "b" : "7F180606C000", "path" : "/opt/rh/rh-mongodb36/root/usr/lib64/libboost_system.so.rh-mongodb36-1.60.0", "elfType" : 3, "buildId" : "57C98F0E18CF8811AEED5ABF8514691E3998D539" }, { "b" : "7F1805E54000", "path" : "/opt/rh/rh-mongodb36/root/usr/lib64/libboost_iostreams.so.rh-mongodb36-1.60.0", "elfType" : 3, "buildId" : "269307C83AA2DA328D8FA46D78B010D9C333904B" }, { "b" : "7F1805A5F000", "path" : "/opt/rh/rh-mongodb36/root/usr/lib64/libtcmalloc.so.rh-mongodb36-4", "elfType" : 3, "buildId" : "3988EC196424AFCB90C4470704FB84B0DA4AE5E6" }, { "b" : "7F1805845000", "path" : "/lib64/libresolv.so.2", "elfType" : 3, "buildId" : "C3B2DD93CD59A17EA97148EC98C2667ADB9987A3" }, { "b" : "7F18055D3000", "path" : "/lib64/libssl.so.10", "elfType" : 3, "buildId" : "3B305C3BA17FE394862E749763F2956C9C890C2E" }, { "b" : "7F1805170000", "path" : "/lib64/libcrypto.so.10", "elfType" : 3, "buildId" : "4CF1939F660008CFA869D8364651F31AACD2C1C4" }, { "b" : "7F1804F68000", "path" : "/lib64/librt.so.1", "elfType" : 3, "buildId" : "CCD4BE566DD5A8FC7FA62B224C14B698F51B0D0D" }, { "b" : "7F1804D64000", "path" : "/lib64/libdl.so.2", "elfType" : 3, "buildId" : "F2C36986E11A291A0D4BCB3A81632B24AE2359EA" }, { "b" : "7F1804A5D000", "path" : "/lib64/libstdc++.so.6", "elfType" : 3, "buildId" : "E2FB6E9C483D89E8E96D73C7CCF3E3A91E91BB81" }, { "b" : "7F180475B000", "path" : "/lib64/libm.so.6", "elfType" : 3, "buildId" : "085D924F5D23B9F15A8AD28B7231EE93C09E13F1" }, { "b" : "7F1804545000", "path" : "/lib64/libgcc_s.so.1", "elfType" : 3, "buildId" : "DAC0179F4555AEFEC9E97476201802FD20C03EC5" }, { "b" : "7F1804329000", "path" : "/lib64/libpthread.so.0", "elfType" : 3, "buildId" : "2B482B3BAE79DEF4E5BC9791BC6BBDAE0E93E359" }, { "b" : "7F1803F5B000", "path" : "/lib64/libc.so.6", "elfType" : 3, "buildId" : "D78066A9C36F5FD63E2F6AC851AE3515C4C9792A" }, { "b" : "7F1803D4B000", "path" : "/lib64/libbz2.so.1", "elfType" : 3, "buildId" : "0C85C0386F0CF41EA39969CF7F58A558D1AD3235" }, { "b" : "7F180745A000", "path" : "/lib64/ld-linux-x86-64.so.2", "elfType" : 3, "buildId" : "27FFD1FBC69569C776E666474EED723395E6D727" }, { "b" : "7F1803AFE000", "path" : "/lib64/libgssapi_krb5.so.2", "elfType" : 3, "buildId" : "C3914975092B29D330453950350E254AA562D642" }, { "b" : "7F1803815000", "path" : "/lib64/libkrb5.so.3", "elfType" : 3, "buildId" : "872EAC9F0CE30D5C4C37ECCCE3C586296D4FA1F0" }, { "b" : "7F1803611000", "path" : "/lib64/libcom_err.so.2", "elfType" : 3, "buildId" : "E4C7298B74FEEADC4DDE40CDD8C4D6B85FE09ADE" }, { "b" : "7F18033DE000", "path" : "/lib64/libk5crypto.so.3", "elfType" : 3, "buildId" : "7856E751772E8538A33113BA62145A8B23314093" }, { "b" : "7F18031CE000", "path" : "/lib64/libkrb5support.so.0", "elfType" : 3, "buildId" : "AED31F16223CE52AE079AB1ED4C09AC4C98F86B8" }, { "b" : "7F1802FCA000", "path" : "/lib64/libkeyutils.so.1", "elfType" : 3, "buildId" : "2E01D5AC08C1280D013AAB96B292AC58BC30A263" }, { "b" : "7F1802DA3000", "path" : "/lib64/libselinux.so.1", "elfType" : 3, "buildId" : "903A0BD0BFB4FEE8C284F41BEB9773DED94CBC52" } ] }}
 mongod(+0x1B12F1A) [0x555ccafeef1a]
 mongod(+0x1B1227E) [0x555ccafee27e]
 mongod(+0x1B12752) [0x555ccafee752]
 libpthread.so.0(+0xF630) [0x7f1804338630]
 libc.so.6(gsignal+0x37) [0x7f1803f91387]
 libc.so.6(abort+0x148) [0x7f1803f92a78]
 mongod(+0x2AD261) [0x555cc9789261]
 mongod(+0x37612D) [0x555cc985212d]
 mongod(+0x375969) [0x555cc9851969]
 mongod(+0x36B368) [0x555cc9847368]
 mongod(+0x36B416) [0x555cc9847416]
 mongod(+0x370D31) [0x555cc984cd31]
 mongod(+0x35ACBD) [0x555cc9836cbd]
 mongod(+0x4CC912) [0x555cc99a8912]
 mongod(+0x343D2D) [0x555cc981fd2d]
 mongod(+0x5485D3) [0x555cc9a245d3]
 mongod(+0x31FC29) [0x555cc97fbc29]
 mongod(+0x322F56) [0x555cc97fef56]
 mongod(+0x2AEC89) [0x555cc978ac89]
 libc.so.6(__libc_start_main+0xF5) [0x7f1803f7d555]
 mongod(+0x30EE45) [0x555cc97eae45]
-----  END BACKTRACE  -----

```

**Comment by akmithal** [comment]
[noobaa_diagnostics_1622783466.tar.gz](https://github.com/noobaa/noobaa-core/files/6595916/noobaa_diagnostics_1622783466.tar.gz)

**Comment by akmithal** [comment]
[Archive.zip](https://github.com/noobaa/noobaa-core/files/6595918/Archive.zip)

**Comment by jeniawhite** [comment]
MVP scope should be on PostgreSQL, this is a deployment with MongoDB.
Will be investigated later on after we handle the NSFS issues.

**Comment by akmithal** [comment]
Closing this bug as not relevant for current HPO MVP GA Scope.
