### ISSUE TITLE
Noobaa operator pod restart in idle system state

### ISSUE THREAD

**Issue by akmithal** [noobaa/noobaa-core#6603]
### Environment info
- NooBaa Version: master-20210622
- Platform: OCP 4.6.16

### Actual behavior
1. Operator pod is restarting

### Expected behavior
1. Operator pod should not restart

### Steps to reproduce
1. Did a warp run which caused defect 6602. 
2. Kept system idle and after some time operator pods restarted twice

Operator pod restarted twice since the warp run completed. 

```
[root@ocp-akshat-1-inf ~]# podn
NAME                                               READY   STATUS        RESTARTS   AGE
noobaa-core-0                                      1/1     Running       0          25h
noobaa-db-pg-0                                     1/1     Running       0          26h
noobaa-default-backing-store-noobaa-pod-b0a5d78b   0/1     Terminating   0          22h
noobaa-endpoint-566488749f-c48tq                   1/1     Running       17         25h
noobaa-operator-656d4f678-lw5k6                    1/1     Running       6          26h
```

Operator pod o/p:

oc logs noobaa-operator-656d4f678-lw5k6  -p  |less -R

```
goroutine 821 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        noobaa-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x10c
panic(0x1f776e0, 0xc00143c1c0)
        /opt/hostedtoolcache/go/1.15.13/x64/src/runtime/panic.go:969 +0x1b9
github.com/sirupsen/logrus.Entry.log(0xc000200540, 0xc000256c30, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        noobaa-operator/vendor/github.com/sirupsen/logrus/entry.go:259 +0x345
github.com/sirupsen/logrus.(*Entry).Log(0xc00052bb90, 0x0, 0xc001a37130, 0x1, 0x1)
        noobaa-operator/vendor/github.com/sirupsen/logrus/entry.go:287 +0xf0
github.com/sirupsen/logrus.(*Entry).Logf(0xc00052bb90, 0x0, 0x1fdc68c, 0x1d, 0xc001a37190, 0x2, 0x2)
        noobaa-operator/vendor/github.com/sirupsen/logrus/entry.go:333 +0xe5
github.com/sirupsen/logrus.(*Entry).Panicf(...)
        noobaa-operator/vendor/github.com/sirupsen/logrus/entry.go:371
github.com/noobaa/noobaa-operator/v5/pkg/util.Panic(0x22c7ce0, 0xc000aee600)
        noobaa-operator/pkg/util/util.go:637 +0xf3
github.com/noobaa/noobaa-operator/v5/pkg/util.KubeDelete(0x22d9880, 0xc000601400, 0x0, 0x0, 0x0, 0x0)
        noobaa-operator/pkg/util/util.go:356 +0x349
github.com/noobaa/noobaa-operator/v5/pkg/backingstore.(*Reconciler).reconcileExistingPods(0xc0010c82a0, 0xc001209dc0, 0xc0009266c0, 0x2)
        noobaa-operator/pkg/backingstore/reconciler.go:1036 +0x185
github.com/noobaa/noobaa-operator/v5/pkg/backingstore.(*Reconciler).reconcilePvPool(0xc0010c82a0, 0x0, 0x1fb375f)
        noobaa-operator/pkg/backingstore/reconciler.go:997 +0x368
github.com/noobaa/noobaa-operator/v5/pkg/backingstore.(*Reconciler).ReconcilePool(0xc0010c82a0, 0x0, 0x0)
        noobaa-operator/pkg/backingstore/reconciler.go:899 +0x9d
github.com/noobaa/noobaa-operator/v5/pkg/backingstore.(*Reconciler).ReconcilePhaseCreating(0xc0010c82a0, 0x0, 0x0)
        noobaa-operator/pkg/backingstore/reconciler.go:369 +0x99
github.com/noobaa/noobaa-operator/v5/pkg/backingstore.(*Reconciler).ReconcilePhases(0xc0010c82a0, 0x0, 0x0)
        noobaa-operator/pkg/backingstore/reconciler.go:242 +0x69
github.com/noobaa/noobaa-operator/v5/pkg/backingstore.(*Reconciler).Reconcile(0xc0010c82a0, 0x6, 0xc00111b0c0, 0x1c, 0x2324020)
        noobaa-operator/pkg/backingstore/reconciler.go:185 +0x98e
github.com/noobaa/noobaa-operator/v5/pkg/controller/backingstore.Add.func1(0xc000bf6900, 0x6, 0xc00111b0c0, 0x1c, 0x4, 0x4, 0xc000a14140, 0xc000fe4920)
        noobaa-operator/pkg/controller/backingstore/backingstore_controller.go:33 +0x113
sigs.k8s.io/controller-runtime/pkg/reconcile.Func.Reconcile(0xc000af2220, 0xc000bf6900, 0x6, 0xc00111b0c0, 0x1c, 0xc000fe4920, 0xc0005c5440, 0xc000fc1688, 0xc000fc1680)
        noobaa-operator/vendor/sigs.k8s.io/controller-runtime/pkg/reconcile/reconcile.go:101 +0x4e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000aa3680, 0x1d98b40, 0xc000f87300, 0x0)
        noobaa-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:235 +0x2a9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000aa3680, 0x203000)
        noobaa-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:209 +0xb0
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc000aa3680)
        noobaa-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:188 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000cecaf0)
        noobaa-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000cecaf0, 0x22c72a0, 0xc0005a3260, 0x1, 0xc0006b83c0)
        noobaa-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000cecaf0, 0x3b9aca00, 0x0, 0x1, 0xc0006b83c0)
        noobaa-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc000cecaf0, 0x3b9aca00, 0xc0006b83c0)
        noobaa-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
        noobaa-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:170 +0x3fa

```

**Comment by akmithal** [comment]
[noobaa_operator_pod_previous.zip](https://github.com/noobaa/noobaa-core/files/6706220/noobaa_operator_pod_previous.zip)
[noobaa_diagnostics_1624508633.tar.gz](https://github.com/noobaa/noobaa-core/files/6706221/noobaa_diagnostics_1624508633.tar.gz)

**Comment by jeniawhite** [comment]
From a brief look seems like something to do with the reconcile of the PV Pool pod.
Needs to be further investigated.

**Comment by liranmauda** [comment]
The decision for deleting the Backingstore was Done due to `Change in Image Pull Secrets detected`:
```
time="2021-06-23T21:02:48Z" level=warning msg="Change in Image Pull Secrets detected: NoobaaSecret(&LocalObjectReference{Name:myregistrykey,}) Spec([{myregistrykey}])" backingstore=noobaa/noobaa-default-backing-store
time="2021-06-23T21:02:48Z" level=info msg="🗑️  Deleting:  \"noobaa-default-backing-store-noobaa-pod-b0a5d78b\"\n"
```
Now when we are trying to delete the `pods/noobaa-default-backing-store-noobaa-pod-b0a5d78b` We get this Painc:
```
time="2021-06-23T21:03:45Z" level=panic msg="☠️  Panic Attack: [] Delete \"https://172.30.0.1:443/api/v1/namespaces/noobaa/pods/noobaa-default-backing-store-noobaa-pod-b0a5d78b\": dial tcp 172.30.0.1:443: connect: connection refused"
E0623 21:03:45.563781
```
The Panic is origins from `KubeDelet`
Now, the question is why do we get `connection refused`?

@akmithal If you have the cluster, can you please provide the `kubectl describe pod/noobaa-default-backing-store-noobaa-pod-b0a5d78b` ?

**Comment by akmithal** [comment]
Hi @liranmauda , I have the backingstore pod in terminating state since a long time now and I ignore it as, as per @jeniawhite , this doesn't affect any of our IO and otherwise operations. This above instance of noobaa-operator doesn't come everytime hence this bug was raised. 

Please find this o/p from my current setup but here the noobaa-operator is not crashed, so I am not sure if this would help:

```
[root@ocp-akshat-1-inf ~]# podn
NAME                                               READY   STATUS        RESTARTS   AGE
noobaa-core-0                                      1/1     Running       0          21h
noobaa-db-pg-0                                     1/1     Running       0          23h
noobaa-default-backing-store-noobaa-pod-2f044807   0/1     Terminating   0          23h
noobaa-endpoint-746df9f5ff-cfcvk                   1/1     Running       0          21h
noobaa-operator-6d5f764f8c-8snpg                   1/1     Running       0          23h
[root@ocp-akshat-1-inf ~]# 
[root@ocp-akshat-1-inf ~]# 
[root@ocp-akshat-1-inf ~]# kubectl describe pod/noobaa-default-backing-store-noobaa-pod-2f044807
Name:                      noobaa-default-backing-store-noobaa-pod-2f044807
Namespace:                 noobaa
Priority:                  0
Node:                      worker0.ocp-akshat-1.cp.fyre.ibm.com/10.17.84.176
Start Time:                Wed, 07 Jul 2021 00:24:28 -0700
Labels:                    app=noobaa
                           pool=noobaa-default-backing-store
Annotations:               k8s.v1.cni.cncf.io/network-status:
                             [{
                                 "name": "",
                                 "interface": "eth0",
                                 "ips": [
                                     "10.254.20.31"
                                 ],
                                 "default": true,
                                 "dns": {}
                             }]
                           k8s.v1.cni.cncf.io/networks-status:
                             [{
                                 "name": "",
                                 "interface": "eth0",
                                 "ips": [
                                     "10.254.20.31"
                                 ],
                                 "default": true,
                                 "dns": {}
                             }]
                           openshift.io/scc: restricted
Status:                    Terminating (lasts 23h)
Termination Grace Period:  30s
IP:                        
IPs:                       <none>
Controlled By:             BackingStore/noobaa-default-backing-store
Containers:
  noobaa-agent:
    Container ID:  
    Image:         noobaa/noobaa-core:master-20210706
    Image ID:      
    Port:          60101/TCP
    Host Port:     0/TCP
    Command:
      /noobaa_init_files/noobaa_init.sh
      agent
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  400Mi
    Requests:
      cpu:     100m
      memory:  400Mi
    Environment:
      CONTAINER_PLATFORM:  KUBERNETES
      AGENT_CONFIG:        <set to the key 'AGENT_CONFIG' in secret 'backing-store-pv-pool-noobaa-default-backing-store'>  Optional: false
    Mounts:
      /noobaa_storage from noobaastorage (rw)
      /usr/local/noobaa/logs from tmp-logs-vol (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-zfl5n (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  tmp-logs-vol:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  noobaastorage:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  noobaa-default-backing-store-noobaa-pvc-2f044807
    ReadOnly:   false
  default-token-zfl5n:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-zfl5n
    Optional:    false
QoS Class:       Guaranteed
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:          <none>

```

**Comment by liranmauda** [comment]
hi @akmithal 
This is not helping in this issue as The operator does not try to reconcile (chance it will not try to `kubedelete`) and will not panic.
I assume that if it will try to reconcile, It will Panic.
now I wonder why the noobaa-default-backing-store-noobaa-pod-2f044807 is in Terminating stat for so long.
Can you please Run:
 - `kubectl describe persistentvolumeclaim/noobaa-default-backing-store-noobaa-pvc-2f044807` 
 and 
 - `kubectl describe persistentvolume/<the value of Volume in the previous describe output>`

**Comment by liranmauda** [comment]
https://github.com/noobaa/noobaa-operator/issues/690

**Comment by akmithal** [comment]
Hi @liranmauda , when is 690 PR be merged ? That way, we might have this problem fixed ?
This is happening even now ( Both noobaa pod restart and backingstore pod restart)

**Comment by liranmauda** [comment]
Hi @akmithal it is not a PR, it is an issue opened by Ulf.
@nimrod-becker WDYT?

**Comment by nimrod-becker** [comment]
I would say we need to clear issues first before we go into RFEs
@liranmauda If its happening now, can you take a look?

**Comment by akmithal** [comment]
Hi @liranmauda , @nimrod-becker , this problem is persisting. It comes on idle setup very frequently.

```
[root@ocp-akshat-1-inf akshat]# podn
NAME                                               READY   STATUS        RESTARTS   AGE
noobaa-core-0                                      1/1     Running       0          14h
noobaa-db-pg-0                                     1/1     Running       0          14h
noobaa-default-backing-store-noobaa-pod-82241f5a   0/1     Terminating   0          12h
noobaa-endpoint-85646d8687-p45z6                   1/1     Running       0          14h
noobaa-operator-7c6585bc76-qcgvf                   1/1     Running       5          14h   -> Multiple restarts
```

```
[root@ocp-akshat-1-inf akshat]# oc get pvc -A
NAMESPACE                       NAME                                               STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                     AGE
ibm-spectrum-scale-csi-driver   scale-fset-pvc                                     Bound    pvc-2595064b-aa7e-4e20-a0a7-53822ff85340   50Gi       RWX            ibm-spectrum-scale-csi-fileset   7d19h
ibm-spectrum-scale-ns           datadir-ibm-spectrum-scale-pmcollector-0           Bound    worker2.ocp-akshat-1.cp.fyre.ibm.com-pv    25Gi       RWO            ibm-spectrum-scale-internal      7d19h
ibm-spectrum-scale-ns           datadir-ibm-spectrum-scale-pmcollector-1           Bound    worker0.ocp-akshat-1.cp.fyre.ibm.com-pv    25Gi       RWO            ibm-spectrum-scale-internal      7d19h
noobaa                          db-noobaa-db-pg-0                                  Bound    pvc-86ff92f2-7260-4a84-b89f-405bf4ded545   50Gi       RWO            ibm-spectrum-scale-csi-fileset   14h
noobaa                          gpfs-vol                                           Bound    pvc-4c27001a-b042-4cd2-bb9a-fc8113b81532   2000Gi     RWX            ibm-spectrum-scale-csi-fileset   14h
noobaa                          noobaa-default-backing-store-noobaa-pvc-82241f5a   Bound    pvc-71bfcdaf-cceb-4fc4-961a-06056473058d   50Gi       RWO            ibm-spectrum-scale-csi-fileset   14h
openshift-image-registry        image-registry-storage                             Bound    registry-storage                           200Gi      RWX                                             86d
[root@ocp-akshat-1-inf akshat]# kubectl describe persistentvolumeclaim/noobaa-default-backing-store-noobaa-pvc-82241f5a
Name:          noobaa-default-backing-store-noobaa-pvc-82241f5a
Namespace:     noobaa
StorageClass:  ibm-spectrum-scale-csi-fileset
Status:        Bound
Volume:        pvc-71bfcdaf-cceb-4fc4-961a-06056473058d
Labels:        app=noobaa
               pool=noobaa-default-backing-store
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: spectrumscale.csi.ibm.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      50Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Mounted By:    noobaa-default-backing-store-noobaa-pod-82241f5a
Events:        <none>
```


```
[root@ocp-akshat-1-inf akshat]# kubectl describe persistentvolume/pvc-71bfcdaf-cceb-4fc4-961a-06056473058d
Name:            pvc-71bfcdaf-cceb-4fc4-961a-06056473058d
Labels:          <none>
Annotations:     pv.kubernetes.io/provisioned-by: spectrumscale.csi.ibm.com
Finalizers:      [kubernetes.io/pv-protection external-attacher/spectrumscale-csi-ibm-com]
StorageClass:    ibm-spectrum-scale-csi-fileset
Status:          Bound
Claim:           noobaa/noobaa-default-backing-store-noobaa-pvc-82241f5a
Reclaim Policy:  Delete
Access Modes:    RWO
VolumeMode:      Filesystem
Capacity:        50Gi
Node Affinity:   <none>
Message:         
Source:
    Type:              CSI (a Container Storage Interface (CSI) volume source)
    Driver:            spectrumscale.csi.ibm.com
    FSType:            
    VolumeHandle:      12597195971916547483;0A0B30A5:6011484F;filesetName=pvc-71bfcdaf-cceb-4fc4-961a-06056473058d;path=/mnt/fs1/spectrum-scale-csi-volume-store/.volumes/pvc-71bfcdaf-cceb-4fc4-961a-06056473058d
    ReadOnly:          false
    VolumeAttributes:      clusterId=12597195971916547483
                           storage.kubernetes.io/csiProvisionerIdentity=1626348145744-8081-spectrumscale.csi.ibm.com
                           volBackendFs=fs1
Events:                <none>
```


The backingstore pod terminates in my setup, so if this is the root cause of this operator crash, this is a regression. It didn't come earlier. 

Uploading must-gather logs as well. 

[must-gather-6.tar.gz](https://github.com/noobaa/noobaa-core/files/6866947/must-gather-6.tar.gz)

**Comment by akmithal** [comment]
Hi @nimrod-becker , can someone look at this now. I upgraded my noobaa version today to master-20210808 and operator pod state goes into CrashLoopBackOff state. 


```
[root@ocp-akshat-1-inf ~]# podn
NAME                                               READY   STATUS             RESTARTS   AGE
noobaa-core-0                                      1/1     Running            0          12m
noobaa-db-pg-0                                     1/1     Running            0          12m
noobaa-default-backing-store-noobaa-pod-1b2d5649   0/1     Terminating        0          5d11h
noobaa-endpoint-6645459cd4-lhjln                   1/1     Running            0          13m
noobaa-operator-55bb4cb96d-j4st6                   0/1     CrashLoopBackOff   4          2m46s
[root@ocp-akshat-1-inf ~]# 
```

**Comment by akmithal** [comment]
[must-gather-0908-1.tar.gz](https://github.com/noobaa/noobaa-core/files/6952068/must-gather-0908-1.tar.gz)

**Comment by liranmauda** [comment]
Hi @akmithal 
This issue is due to config map.
We are trying to set a field in an uninitialised map. 
This issue belongs to the operator.

**Comment by kfir-payne** [comment]
@liranmauda @akmithal this is not related to this bug, I have opened a new issue at the operator project.
https://github.com/noobaa/noobaa-operator/issues/712

**Comment by kfir-payne** [comment]
link to a PR with a bug fix to that issue: https://github.com/noobaa/noobaa-operator/pull/713

**Comment by liranmauda** [comment]
@akmithal 
Can you see if it still happens after the fix in noobaa/noobaa-operator#713 ?
