### ISSUE TITLE
Endpoint panic "Error: Connection terminated unexpectedly", idle setup

### ISSUE THREAD

**Issue by akmithal** [noobaa/noobaa-core#6617]
### Environment info
- NooBaa Version: master-20210629
- Platform: OCP 4.6.16

### Actual behavior
1. Endpoint pods along with other node pods crashed on idle system

### Expected behavior
1. No pods should restart

### Steps to reproduce
1. Kept system idle

```
Jun-28 23:20:03.766 [Endpoint/8] [ERROR] CONSOLE:: RPC._on_request: ERROR srv object_api.add_endpoint_report reqid 3104@fcall://fcall(7ojni7uw) connid fcall://fcall(7ojni7uw) Error: Connection terminated unexpectedly
    at Connection.<anonymous> (/root/node_modules/noobaa-core/node_modules/pg/lib/client.js:132:73)
    at Object.onceWrapper (events.js:421:28)
    at Connection.emit (events.js:315:20)
    at Connection.EventEmitter.emit (domain.js:467:12)
    at Socket.<anonymous> (/root/node_modules/noobaa-core/node_modules/pg/lib/connection.js:107:12)
    at Socket.emit (events.js:327:22)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Jun-28 23:20:03.767 [Endpoint/8] [ERROR] CONSOLE:: PANIC: process uncaughtException Error: Connection terminated unexpectedly
    at Connection.<anonymous> (/root/node_modules/noobaa-core/node_modules/pg/lib/client.js:132:73)
    at Object.onceWrapper (events.js:421:28)
    at Connection.emit (events.js:315:20)
    at Connection.EventEmitter.emit (domain.js:467:12)
    at Socket.<anonymous> (/root/node_modules/noobaa-core/node_modules/pg/lib/connection.js:107:12)
    at Socket.emit (events.js:327:22)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)



######################################################################
Mon Jun 28 23:20:03 UTC 2021 NooBaa: Process exited RIP (RC=1)
######################################################################

```

### More information - Screenshots / Logs / Other output

```
[root@ocp-akshat-1-inf ~]# podn
NAME                                               READY   STATUS             RESTARTS   AGE
noobaa-core-0                                      1/1     Running            0          21h
noobaa-db-pg-0                                     0/1     CrashLoopBackOff   55         21h
noobaa-default-backing-store-noobaa-pod-be771f93   0/1     Terminating        0          17h
noobaa-endpoint-59d548d866-9wfml                   1/1     Running            1          21h
noobaa-operator-57d449689c-9qkfn                   1/1     Running            3          22h
```

**Comment by akmithal** [comment]
[endpoint_idle_29june.zip](https://github.com/noobaa/noobaa-core/files/6730583/endpoint_idle_29june.zip)

**Comment by jeniawhite** [comment]
In this case the database is down and this is why the endpoints cannot connect to it and are crashing.
Would be great if you could attach noobaa-db-pg-0 pod logs with --previous as well and describe the resource.
It looks like the cause is the DB in that case.

**Comment by akmithal** [comment]
Hi @jeniawhite , The noobaa-db-pg-0 pod doesn't have any meaningful logs as you can see it crashed very very frequently. I don't have the describe o/p, can't this be determined from the logs ? May be an enhancement to our noobaa diagnose design if it is required for debugging.

**Comment by akmithal** [comment]
Closing this bug as it is not reproducible with builds master-20210812 onwards.
