### ISSUE TITLE
Unable to list objects in a bucket using Amazon S3 Java client...

### ISSUE THREAD

**Issue by msmiths** [noobaa/noobaa-core#6620]
### Environment info
- NooBaa Version: 

```
INFO[0000] CLI version: 5.7.0                           
INFO[0000] noobaa-image: noobaa/noobaa-core:5.7.0       
INFO[0000] operator-image: noobaa/noobaa-operator:5.7.0 
```

- Platform: OpenShift 4.7.4 - with NooBaa deployed via the OpenShift Container Storage operator (v4.7.1).

### Actual behavior
1. Attempting to list objects in a bucket using the Amazon S3 java client results in a `com.amazonaws.services.s3.model.AmazonS3Exception` being thrown. The stack trace is as follows:
```
com.amazonaws.services.s3.model.AmazonS3Exception: Service Unavailable (Service: Amazon S3; Status Code: 503; Error Code: 503 Service Unavailable; Request ID: null; S3 Extended Request ID: null; Proxy: null), S3 Extended Request ID: null
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1819)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1403)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1372)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5437)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5384)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5378)
	at com.amazonaws.services.s3.AmazonS3Client.listObjectsV2(AmazonS3Client.java:970)
	at com.amazonaws.services.s3.AmazonS3Client.listObjectsV2(AmazonS3Client.java:933)
	at com.ibm.ws.intelligentops.util.Test.main(Test.java:125)
```

### Expected behavior
1. The list of objects in the bucket should be returned.

### Steps to reproduce
1. Code is as follows:
```
package com.ibm.ws.intelligentops.util;

import java.util.List;

import com.amazonaws.auth.AWSCredentialsProvider;
import com.amazonaws.auth.AWSStaticCredentialsProvider;
import com.amazonaws.auth.BasicAWSCredentials;
import com.amazonaws.client.builder.AwsClientBuilder.EndpointConfiguration;
import com.amazonaws.regions.Regions;
import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.AmazonS3ClientBuilder;
import com.amazonaws.services.s3.model.Bucket;
import com.amazonaws.services.s3.model.ListObjectsV2Result;
import com.amazonaws.services.s3.model.S3ObjectSummary;

public class Test {
    // OpenShift Container Storage - NooBaa
    public static final String ENDPOINT = "https://s3-openshift-storage.apps.abcde.cp.fyre.ibm.com";
    public static final String AWS_ACCESS_KEY_ID = "XXXXX";
    public static final String AWS_SECRET_ACCESS_KEY = "XXXXX";

    public static final String BUCKET_NAME = "wsa.healing.dumps";
    public static final String KEY_NAME = "demo-microprofile-openapi-2.0.war";
    public static final Regions region = Regions.US_EAST_1;

    public static final BasicAWSCredentials awsCreds = new BasicAWSCredentials(AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY);
    public static final AWSCredentialsProvider credentialsProvider = new AWSStaticCredentialsProvider(awsCreds);

    public static void main(String[] args) {
        try {
            // AmazonS3 Client
            final AmazonS3 s3Client = AmazonS3ClientBuilder.standard()
                .withEndpointConfiguration(new EndpointConfiguration(ENDPOINT, region.getName()))
                .withCredentials(credentialsProvider)
                .build();

            List<Bucket> buckets = s3Client.listBuckets();
            for (Bucket bucket : buckets) {
                System.out.println("Bucket Name: " + bucket.getName());
                System.out.println("\tObjects: ");
                ListObjectsV2Result result = s3Client.listObjectsV2(bucket.getName());
                for (S3ObjectSummary summary : result.getObjectSummaries()) {
                    System.out.println(String.format("\t\t%s (size: %s, owner: %s)", summary.getKey(), summary.getSize(), summary.getOwner()));
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```

### More information - Screenshots / Logs / Other output

I am able to list the objects in the bucket using both the AWS CLI and the boto3 python client. It is only when using the Amazon S3 java client that I am seeing this issue.

**Comment by msmiths** [comment]
User error... closing.

**Comment by guymguym** [comment]
Thanks @msmiths !
