### ISSUE TITLE
Endpoint logs: Postgres client ERROR messages about idx_btree_tiers_system_name_deleted  already exists

### ISSUE THREAD

**Issue by rkomandu** [noobaa/noobaa-core#6661]
### Environment info
- NooBaa Version: **VERSION**
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify**

oc version
Client Version: 4.7.8
Server Version: 4.7.8
Kubernetes Version: v1.20.0+7d0a2b2

noobaa version
INFO[0000] CLI version: 5.9.0
INFO[0000] noobaa-image: noobaa/noobaa-core:master-20210628
INFO[0000] operator-image: noobaa/noobaa-operator:5.9.0

In the endpoint logs observed the below 

[32mJul-13 6:54:19.185[35m [Endpoint/10] [36m   [L0][39m core.util.postgres_client:: creating index system_name_deleted in table buckets
[32mJul-13 6:54:19.186[35m [Endpoint/10] [36m   [L0][39m core.util.postgres_client:: creating index owner_secret in table clusters
[32mJul-13 6:54:19.188[35m [Endpoint/10] [31m[ERROR][39m core.util.postgres_client:: postgres_client: T00000000|Q00000013: failed with error: error: relation "idx_btree_tiers_system_name_deleted" already exists
    at Parser.parseErrorMessage (/root/node_modules/[4mnoobaa-core[24m/node_modules/[4mpg[24m/node_modules/[4mpg-protocol[24m/dist/parser.js:287:98)
    at Parser.handlePacket (/root/node_modules/[4mnoobaa-core[24m/node_modules/[4mpg[24m/node_modules/[4mpg-protocol[24m/dist/parser.js:126:29)
    at Parser.parse (/root/node_modules/[4mnoobaa-core[24m/node_modules/[4mpg[24m/node_modules/[4mpg-protocol[24m/dist/parser.js:39:38)
    at Socket.<anonymous> (/root/node_modules/[4mnoobaa-core[24m/node_modules/[4mpg[24m/node_modules/[4mpg-protocol[24m/dist/index.js:11:42)
[90m    at Socket.emit (events.js:315:20)[39m
[90m    at Socket.EventEmitter.emit (domain.js:467:12)[39m
[90m    at addChunk (internal/streams/readable.js:309:12)[39m
[90m    at readableAddChunk (internal/streams/readable.js:284:9)[39m
[90m    at Socket.Readable.push (internal/streams/readable.js:223:10)[39m
[90m    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)[39m {
  length: [33m117[39m,
  severity: [32m'ERROR'[39m,
  code: [32m'42P07'[39m,
  detail: [90mundefined[39m,
  hint: [90mundefined[39m,
  position: [90mundefined[39m,
  internalPosition: [90mundefined[39m,
  internalQuery: [90mundefined[39m,
  where: [90mundefined[39m,
  schema: [90mundefined[39m,
  table: [90mundefined[39m,
  column: [90mundefined[39m,
  dataType: [90mundefined[39m,
  constraint: [90mundefined[39m,
  file: [32m'index.c'[39m,
  line: [32m'863'[39m,
  routine: [32m'index_create'[39m
}
[32mJul-13 6:54:19.188[35m [Endpoint/10] [31m[ERROR][39m core.util.postgres_client:: postgres_client: T00000000|Q00000014: failed with error: error: relation "idx_btree_accounts_email_deleted" already exists
    at Parser.parseErrorMessage (/root/node_modules/[4mnoobaa-core[24m/node_modules/[4mpg[24m/node_modules/[4mpg-protocol[24m/dist/parser.js:287:98)
    at Parser.handlePacket (/root/node_modules/[4mnoobaa-core[24m/node_modules/[4mpg[24m/node_modules/[4mpg-protocol[24m/dist/parser.js:126:29)
    at Parser.parse (/root/node_modules/[4mnoobaa-core[24m/node_modules/[4mpg[24m/node_modules/[4mpg-protocol[24m/dist/parser.js:39:38)
    at Socket.<anonymous> (/root/node_modules/[4mnoobaa-core[24m/node_modules/[4mpg[24m/node_modules/[4mpg-protocol[24m/dist/index.js:11:42)
[90m    at Socket.emit (events.js:315:20)[39m
[90m    at Socket.EventEmitter.emit (domain.js:467:12)[39m
[90m    at addChunk (internal/streams/readable.js:309:12)[39m
[90m    at readableAddChunk (internal/streams/readable.js:284:9)[39m
[90m    at Socket.Readable.push (internal/streams/readable.js:223:10)[39m
  length: [33m114[39m,
  severity: [32m'ERROR'[39m,
  code: [32m'42P07'[39m,
  detail: [90mundefined[39m,
  hint: [90mundefined[39m,
  position: [90mundefined[39m,
  internalPosition: [90mundefined[39m,
  internalQuery: [90mundefined[39m,
  where: [90mundefined[39m,
  schema: [90mundefined[39m,
  table: [90mundefined[39m,
  column: [90mundefined[39m,
  dataType: [90mundefined[39m,
  constraint: [90mundefined[39m,
  file: [32m'index.c'[39m,
  line: [32m'863'[39m,
  routine: [32m'index_create'[39m
}
[32mJul-13 6:54:19.189[35m [Endpoint/10] [31m[ERROR][39m core.util.postgres_client:: postgres_client: T00000000|Q00000015: failed with error: error: relation "idx_btree_systems_name_deleted" already exists
    at Parser.parseErrorMessage (/root/node_modules/[4mnoobaa-core[24m/node_modules/[4mpg[24m/node_modules/[4mpg-protocol[24m/dist/parser.js:287:98)
    at Parser.handlePacket (/root/node_modules/[4mnoobaa-core[24m/node_modules/[4mpg[24m/node_modules/[4mpg-protocol[24m/dist/parser.js:126:29)
    at Parser.parse (/root/node_modules/[4mnoobaa-core[24m/node_modules/[4mpg[24m/node_modules/[4mpg-protocol[24m/dist/parser.js:39:38)
    at Socket.<anonymous> (/root/node_modules/[4mnoobaa-core[24m/node_modules/[4mpg[24m/node_modules/[4mpg-protocol[24m/dist/index.js:11:42)
[90m    at Socket.emit (events.js:315:20)[39m
[90m    at Socket.EventEmitter.emit (domain.js:467:12)[39m
[90m    at addChunk (internal/streams/readable.js:309:12)[39m
[90m    at readableAddChunk (internal/streams/readable.js:284:9)[39m
[90m    at Socket.Readable.push (internal/streams/readable.js:223:10)[39m
[90m    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)[39m {
  length: [33m112[39m,
  severity: [32m'ERROR'[39m,
  code: [32m'42P07'[39m,
  detail: [90mundefined[39m,
  hint: [90mundefined[39m,
  position: [90mundefined[39m,
  internalPosition: [90mundefined[39m,
  internalQuery: [90mundefined[39m,
  where: [90mundefined[39m,
  schema: [90mundefined[39m,
  table: [90mundefined[39m,
  column: [90mundefined[39m,
... 

### Actual behavior
1. As per discussion with Noobaa team, it was mentioned these are ok and not real ERROR.. Asked Noobaa team to change to WARN or INFO level if these are not real errors. Hence this defect. 
2

### Expected behavior
1.

### Steps to reproduce
1. 

oc get pods
NAME                                               READY   STATUS    RESTARTS   AGE
noobaa-core-0                                      1/1     Running   0          3h23m
noobaa-db-pg-0                                     1/1     Running   0          3h24m
noobaa-default-backing-store-noobaa-pod-269857ea   1/1     Running   0          6d21h
noobaa-endpoint-8cbcd8545-mn5dt                    1/1     Running   0          3h21m
noobaa-operator-854c5fc67d-dd46k                   1/1     Running   3          3h21m 

[endpoint-log.txt](https://github.com/noobaa/noobaa-core/files/6808082/endpoint-log.txt)

**Comment by rkomandu** [comment]
@jackyalbo @jeniawhite 

This is still visible in the 20210724 noobaa build . We decided to have the Label changes from Error to WARN or INFO 

Jul-27 11:59:55.291 [Endpoint/9] [ERROR] core.util.postgres_client:: postgres_client: T00000000|Q00000604: failed with error: error: relation "idx_btree_endpointgroup
reports_start_time_aggregated_time_aggre" already exists
    at Parser.parseErrorMessage (/root/node_modules/noobaa-core/node_modules/pg/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/root/node_modules/noobaa-core/node_modules/pg/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/root/node_modules/noobaa-core/node_modules/pg/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/root/node_modules/noobaa-core/node_modules/pg/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  length: 145,
  severity: 'ERROR',
  code: '42P07',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'index.c',
  line: '863',
  routine: 'index_create'
}

**Comment by jackyalbo** [comment]
This is really weird. Can you rsh to this endpoint. and copy /root/node_module/noobaa/src/util/postgres_client.js and upload or send it to me?

**Comment by rkomandu** [comment]
It is in this directory /root/node_modules/noobaa-core/src/util
sh-4.4# ls -lrt postgres_client.js
-rwxrwxr-x. 1 root root 54744 Jun  9 23:01 postgres_client.js

[postgres_client.zip](https://github.com/noobaa/noobaa-core/files/6887207/postgres_client.zip)

**Comment by rkomandu** [comment]
Somehow it doesn't allow the js file to upload directly, hence zip needs to be done..

**Comment by jackyalbo** [comment]
Ok so I think this file is pretty old - I think at lease a month old.. It doen't have even the performance fixes.
Can you check you are using the right build?

**Comment by rkomandu** [comment]
using the latest build of 0724 

noobaa version
INFO[0000] CLI version: 5.9.0
INFO[0000] noobaa-image: noobaa/noobaa-core:master-20210724
INFO[0000] operator-image: noobaa/noobaa-operator:5.9.0

Looks like the core,db didn't get upgraded in the OCS method as we try to change csv file only for the operator.. i thought it was one step.. So let me see tomorrow and then will update

**Comment by rkomandu** [comment]
I am no longer seeing this error as just installed 0801. Would wait for a day or two and then will try to close it if non occurring

**Comment by liranmauda** [comment]
Hi @rkomandu 
If this is not reproducible, can we close the issue?

**Comment by madhuthorat** [comment]
Please close it as HPO is discontinued and hence we won't have containerized Noobaa validation with ODF.
