### ISSUE TITLE
Warp caused "Error: Attempted to acc ess archived or sparse file"

### ISSUE THREAD

**Issue by akmithal** [noobaa/noobaa-core#6729]
### Environment info
- NooBaa Version: ODF operator 4.9.0 - 142.ci 
- Platform: OCP 4.8.9

### Actual behavior
1. Warp failure "The operation is not valid for the  current state of the object."

### Expected behavior
1. No warp errors

### Steps to reproduce
1. Started warp run for 9M object size

```
Sep-21 5:24:02.360 [Endpoint/9] [ERROR] core.endpoint.s3.s3_rest:: S3 ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>InvalidObjectState</Code><Message>The operation is not valid for the
 current state of the object.</Message><Resource>/bucket-1/gzScqTTO/12.rZWPKb0Z%290ULHi8Y.rnd</Resource><RequestId>kttmu1pj-ak3yi6-toh</RequestId></Error> GET /bucket-1/gzScqTTO/12.rZWPKb0Z%290UL
Hi8Y.rnd {"user-agent":"MinIO (linux; amd64) minio-go/v7.0.11 warp/0.3.43","authorization":"AWS4-HMAC-SHA256 Credential=ubZVZcTm8a263swlNnxb/20210921/us-east-1/s3/aws4_request, SignedHeaders=host
;x-amz-content-sha256;x-amz-date, Signature=e8234d92f2f94911cfd19f32a234be4df37afa4e60cea19f54a7c9a336517ebc","x-amz-content-sha256":"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b
855","x-amz-date":"20210921T052402Z","host":"s3-openshift-storage.apps.ocp-akshat-1.cp.fyre.ibm.com","x-forwarded-host":"s3-openshift-storage.apps.ocp-akshat-1.cp.fyre.ibm.com","x-forwarded-port"
:"443","x-forwarded-proto":"https","forwarded":"for=10.17.66.193;host=s3-openshift-storage.apps.ocp-akshat-1.cp.fyre.ibm.com;proto=https","x-forwarded-for":"10.17.66.193"} Error: Attempted to acc
ess archived or sparse file
    at NamespaceFS._fail_if_archived_or_sparse_file (/root/node_modules/noobaa-core/src/sdk/namespace_fs.js:1280:19)
    at async NamespaceFS.read_object_stream (/root/node_modules/noobaa-core/src/sdk/namespace_fs.js:477:13)
    at async ObjectSDK.read_object_stream (/root/node_modules/noobaa-core/src/sdk/object_sdk.js:396:23)
    at async Object.get_object [as handler] (/root/node_modules/noobaa-core/src/endpoint/s3/ops/s3_get_object.js:115:19)
    at async handle_request (/root/node_modules/noobaa-core/src/endpoint/s3/s3_rest.js:149:19)
    at async Object.s3_rest [as handler] (/root/node_modules/noobaa-core/src/endpoint/s3/s3_rest.js:68:9)
```

I am on downstream code level and I expect this defect to be fixed long back but raising bug so that we don't miss out on this issue. 

Either it is a regression OR I am on older Noobaa code level in which case, we would need a newer merged code in ODF. 
This issue was fixed on upstream noobaa code - master-20210812 
https://github.com/noobaa/noobaa-core/issues/6680

**Comment by akmithal** [comment]
@nimrod-becker , @jeniawhite : Kindly suggest how to ensure we are on latest Noobaa code level when we take downstream build approach.

**Comment by akmithal** [comment]
[noobaa_diagnostics_1632201734.tar.gz](https://github.com/noobaa/noobaa-core/files/7207930/noobaa_diagnostics_1632201734.tar.gz)

**Comment by jeniawhite** [comment]
@akmithal 
Saw that you were using a build that doesn't have the commit that removed this issue.
As mentioned above you shouldn't be able to see these errors after commit #6680.

**Comment by nimrod-becker** [comment]
Closing per last comment
@akmithal
