### ISSUE TITLE
IO failed for 100GB, Error - "We encountered an internal error"

### ISSUE THREAD

**Issue by akmithal** [noobaa/noobaa-core#6756]
### Environment info
- NooBaa Version: 188.ci 
- Platform: OCP 4.8.9

### Actual behavior
1. IO failed for 100GB file

### Expected behavior
1. IO should not fail

### Steps to reproduce
1. Deployed downstream build 188.ci using ODF operator
2. Started sync upload of 100GB file 

`upload failed: ./big_file_100GB to s3://bucket-1/big_file_100GB Connection was closed before we received a valid response from endpoint URL: "https://s3-openshift-storage.apps.ocp-akshat-1.cp.fyre.ibm.com/bucket-1/big_file_100GB?uploadId=b9eb0e87-954c-44b7-8dd6-e2255af67777&partNumber=1228".`

```
Oct-13 10:17:19.551 [Endpoint/14] [ERROR] core.endpoint.s3.s3_rest:: S3 ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.<
/Message><Resource>/bucket-1/big_file_100GB?uploadId=b9eb0e87-954c-44b7-8dd6-e2255af67777&amp;partNumber=1228</Resource><RequestId>kupcyhga-29jx07-9mh</RequestId></Error> PUT /bucket-1/big_file_100GB?uploadId=b
9eb0e87-954c-44b7-8dd6-e2255af67777&partNumber=1228 {"accept-encoding":"identity","user-agent":"aws-cli/2.1.29 Python/3.8.8 Linux/4.18.0-305.19.1.el8_4.x86_64 exe/x86_64.rhel.8 prompt/off command/s3.sync","cont
ent-md5":"gsQpPCLbi5D/MbI9Um8MmA==","expect":"100-continue","x-amz-date":"20211013T101610Z","x-amz-content-sha256":"UNSIGNED-PAYLOAD","authorization":"AWS4-HMAC-SHA256 Credential=eUEqexB7B0zYWROHCBYB/20211013/u
s-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=c6ea3b8eb120e42917439bf450593d02e68f4a8ae5e08965b052d0289ff95c1c","content-length":"16777216","host":"s3-opens
hift-storage.apps.ocp-akshat-1.cp.fyre.ibm.com","x-forwarded-host":"s3-openshift-storage.apps.ocp-akshat-1.cp.fyre.ibm.com","x-forwarded-port":"443","x-forwarded-proto":"https","forwarded":"for=10.17.66.193;hos
t=s3-openshift-storage.apps.ocp-akshat-1.cp.fyre.ibm.com;proto=https","x-forwarded-for":"10.17.66.193"} Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at IncomingMessage.onclose (internal/streams/end-of-stream.js:117:38)
    at IncomingMessage.emit (events.js:400:28)
    at IncomingMessage.emit (domain.js:470:12)
    at abortIncoming (_http_server.js:566:9)
    at socketOnClose (_http_server.js:559:3)
    at TLSSocket.emit (events.js:412:35)
    at TLSSocket.emit (domain.js:470:12)
    at net.js:675:12
    at Socket.done (_tls_wrap.js:563:7)
    at Object.onceWrapper (events.js:520:26)
```

There are multiple restarts of Noobaa operator, OCS operator and ODF operator

```
[root@ocp-akshat-1-inf akshat]# podo
NAME                                               READY   STATUS             RESTARTS   AGE
noobaa-core-0                                      1/1     Running            0          23m
noobaa-db-pg-0                                     1/1     Running            0          63m
noobaa-default-backing-store-noobaa-pod-7dc5521a   1/1     Running            0          60m
noobaa-endpoint-c4dbfb567-8wj2f                    1/1     Running            0          54m
noobaa-operator-769c6c8f67-qkx27                   0/1     CrashLoopBackOff   13         67m
ocs-metrics-exporter-7756794cbc-6899b              1/1     Running            0          67m
ocs-operator-5f948b58dc-mfnck                      1/1     Running            12         67m
odf-console-5cbd7f6c84-n4fqp                       1/1     Running            0          67m
odf-operator-controller-manager-6768cb46b7-85rph   1/2     CrashLoopBackOff   15         67m
rook-ceph-operator-878d555f4-gwhpl                 1/1     Running            0          67m
```

I don't have access to Noobaa CLI to collect noobaa diagnose and must-gather command is giving timeout errors. Hence manually copying endpoint logs.

**Comment by jeniawhite** [comment]
@akmithal 
Sadly there is less than a second of history on defect_6756_s3_debug_output.zip (only the last terminal page, I assume).
There is no information regarding the reason.

**Comment by ketankhurana64** [comment]
This test was re-executed on completely new cluster with OCP 4.8.13, CNSA 5113 and ODF 191.ci with noobaa deployed using noobaa_cr.yaml and we're able to replicate it.

Attaching the logs
[endpointlog_200M.txt](https://github.com/noobaa/noobaa-core/files/7371035/endpointlog_200M.txt)
[console_log_200M.txt](https://github.com/noobaa/noobaa-core/files/7371036/console_log_200M.txt)

[must-gather.local.49677808772537652_200M_io.tar.gz](https://github.com/noobaa/noobaa-core/files/7371046/must-gather.local.49677808772537652_200M_io.tar.gz)

**Comment by akmithal** [comment]
Hi @nimrod-becker , please remove Request verification label from this defect.

**Comment by akmithal** [comment]
Moving this from 6848 defect:

Hi @romayalon , @jeniawhite , @nimrod-becker : I am getting following errors while taking build: `5.9_nsfsfixes-20220208`

We have seen this even earlier - `code: 'ERR_STREAM_PREMATURE_CLOSE'`

```
Feb-14 7:45:56.751 [Endpoint/14] [ERROR] core.sdk.namespace_fs:: _upload_stream had error:  Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at new NodeError (internal/errors.js:322:7)
    at IncomingMessage.onclose (internal/streams/end-of-stream.js:117:38)
    at IncomingMessage.emit (events.js:400:28)
    at IncomingMessage.emit (domain.js:475:12)
    at abortIncoming (_http_server.js:569:9)
    at socketOnClose (_http_server.js:562:3)
    at TLSSocket.emit (events.js:412:35)
    at TLSSocket.emit (domain.js:475:12)
    at net.js:686:12
    at Socket.done (_tls_wrap.js:564:7) {
  code: 'ERR_STREAM_PREMATURE_CLOSE'
}
Feb-14 7:45:56.768 [Endpoint/14]    [L0] core.endpoint.s3.ops.s3_put_object:: PUT OBJECT bucket-51 axSawPSI/1858.vVX(eATV0TRdPGjK.rnd  
Feb-14 7:45:56.769 [Endpoint/14] [ERROR] core.endpoint.s3.s3_rest:: S3 ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>InternalError</Code><Message>We encountered an internal erro
r. Please try again.</Message><Resource>/bucket-11/OcsLm0fH/8.rKRBiTByHwgSmruF.rnd</Resource><RequestId>kzme4vk9-9eqh3t-n3g</RequestId></Error> PUT /bucket-11/OcsLm0fH/8.rKRBiTByHwgSmruF.r
nd {"user-agent":"MinIO (linux; amd64) minio-go/v7.0.11 warp/0.5.2","content-length":"20000000","authorization":"AWS4-HMAC-SHA256 Credential=HhYucHy6z3qOgMDmBz6b/20220214/us-east-1/s3/aws4
_request, SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date, Signature=ab723b517f84810c8636702201bd9907438ce7c66140fcc2e686180c6e81b495","content-type":"application/octet-str
eam","x-amz-content-sha256":"UNSIGNED-PAYLOAD","x-amz-date":"20220214T074421Z","host":"s3-openshift-storage.apps.cluster-ocp1.cp.fyre.ibm.com","x-forwarded-host":"s3-openshift-storage.apps
.cluster-ocp1.cp.fyre.ibm.com","x-forwarded-port":"443","x-forwarded-proto":"https","forwarded":"for=10.13.2.40;host=s3-openshift-storage.apps.cluster-ocp1.cp.fyre.ibm.com;proto=https","x-
forwarded-for":"10.13.2.40"} Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at new NodeError (internal/errors.js:322:7)
    at IncomingMessage.onclose (internal/streams/end-of-stream.js:117:38)
    at IncomingMessage.emit (events.js:400:28)
    at IncomingMessage.emit (domain.js:475:12)
    at abortIncoming (_http_server.js:569:9)
    at socketOnClose (_http_server.js:562:3)
    at TLSSocket.emit (events.js:412:35)
    at TLSSocket.emit (domain.js:475:12)
    at net.js:686:12
    at Socket.done (_tls_wrap.js:564:7)
```

Errors while doing warp:

```
warp: <ERROR> upload error: Put "https://s3-openshift-storage.apps.cluster-ocp1.cp.fyre.ibm.com/bucket-41/xLlKprX0/1.whS6xSWZU5TvCMTC.rnd?partNumber=8&uploadId=fd295d7b-76f1-46da-81af-6a65ba480cc4": Connection closed by foreign host https://s3-openshift-storage.apps.cluster-ocp1.cp.fyre.ibm.com/bucket-41/xLlKprX0/1.whS6xSWZU5TvCMTC.rnd?partNumber=8&uploadId=fd295d7b-76f1-46da-81af-6a65ba480cc4. Retry again.
warp: <ERROR> upload error: Put "https://s3-openshift-storage.apps.cluster-ocp1.cp.fyre.ibm.com/bucket-41/F1ZQcQ1E/2.SrxXTOn77SF8q20T.rnd?partNumber=8&uploadId=00b2e572-b915-4800-9d80-a6efccd08e4c": Connection closed by foreign host https://s3-openshift-storage.apps.cluster-ocp1.cp.fyre.ibm.com/bucket-41/F1ZQcQ1E/2.SrxXTOn77SF8q20T.rnd?partNumber=8&uploadId=00b2e572-b915-4800-9d80-a6efccd08e4c. Retry again.
warp: <ERROR> upload error: Put "https://s3-openshift-storage.apps.cluster-ocp1.cp.fyre.ibm.com/bucket-41/RQggYXge/2.Y2fIAJyoHZO4AnsR.rnd?partNumber=8&uploadId=babea8d9-a118-4c9e-b13f-fd42c9206b2c": Connection closed by foreign host https://s3-openshift-storage.apps.cluster-ocp1.cp.fyre.ibm.com/bucket-41/RQggYXge/2.Y2fIAJyoHZO4AnsR.rnd?partNumber=8&uploadId=babea8d9-a118-4c9e-b13f-fd42c9206b2c. Retry again.
warp: <ERROR> upload error: Put "https://s3-openshift-storage.apps.cluster-ocp1.cp.fyre.ibm.com/bucket-41/sgyllXqa/2.cFHE1VQlrt7Q%28MU0.rnd?partNumber=8&uploadId=19c65361-d658-48b3-9d96-3b30d08d7258": Connection closed by foreign host https://s3-openshift-storage.apps.cluster-ocp1.cp.fyre.ibm.com/bucket-41/sgyllXqa/2.cFHE1VQlrt7Q%28MU0.rnd?partNumber=8&uploadId=19c65361-d658-48b3-9d96-3b30d08d7258. Retry again.
warp: <ERROR> upload error: Put "https://s3-openshift-storage.apps.cluster-ocp1.cp.fyre.ibm.com/bucket-41/16KJlVpR/2.itDobjhlTpZl4IQP.rnd?partNumber=8&uploadId=a6da3679-549d-4960-a4a2-f9fa7a9d8844": Connection closed by foreign host https://s3-openshift-storage.apps.cluster-ocp1.cp.fyre.ibm.com/bucket-41/16KJlVpR/2.itDobjhlTpZl4IQP.rnd?partNumber=8&uploadId=a6da3679-549d-4960-a4a2-f9fa7a9d8844. Retry again.
warp: <ERROR> upload error: Put "https://s3-openshift-storage.apps.cluster-ocp1.cp.fyre.ibm.com/bucket-41/rP%28JOojN/2.UMk2DhOpZRScZCi5.rnd?partNumber=8&uploadId=f18394e5-582e-4ce2-98d1-ac8c540539cc": Connection closed by foreign host https://s3-openshift-storage.apps.cluster-ocp1.cp.fyre.ibm.com/bucket-41/rP%28JOojN/2.UMk2DhOpZRScZCi5.rnd?partNumber=8&uploadId=f18394e5-582e-4ce2-98d1-ac8c540539cc. Retry again.
warp: <ERROR> upload error: 504 Gateway Time-out
warp: <ERROR> upload error: 504 Gateway Time-out
warp: <ERROR> upload error: 504 Gateway Time-out
warp: <ERROR> upload error: Put "https://s3-openshift-storage.apps.cluster-ocp1.cp.fyre.ibm.com/bucket-41/sUTYgqBM/5.ZIRpy8fx5JcnslTz.rnd?partNumber=8&uploadId=3e702ebb-e2a5-43a9-aee9-edc3315584d8": Connection closed by foreign host https://s3-openshift-storage.apps.cluster-ocp1.cp.fyre.ibm.com/bucket-41/sUTYgqBM/5.ZIRpy8fx5JcnslTz.rnd?partNumber=8&uploadId=3e702ebb-e2a5-43a9-aee9-edc3315584d8. Retry again.
warp: <ERROR> upload error: Put "https://s3-openshift-storage.apps.cluster-ocp1.cp.fyre.ibm.com/bucket-41/O8GRsJB2/5.5bbtB1L3zPavbndS.rnd?partNumber=8&uploadId=c0dc09f0-a08f-4aa7-8105-48bdda5ff11b": Connection closed by foreign host https://s3-openshift-storage.apps.cluster-ocp1.cp.fyre.ibm.com/bucket-41/O8GRsJB2/5.5bbtB1L3zPavbndS.rnd?partNumber=8&uploadId=c0dc09f0-a08f-4aa7-8105-48bdda5ff11b. Retry again.
warp: <ERROR> upload error: Put "https://s3-openshift-storage.apps.cluster-ocp1.cp.fyre.ibm.com/bucket-41/QoQN663R/5.zwVfOhHlH01VGJAW.rnd?partNumber=8&uploadId=b9902c56-fc69-4228-a307-e037bc039629": Connection closed by foreign host https://s3-openshift-storage.apps.cluster-ocp1.cp.fyre.ibm.com/bucket-41/QoQN663R/5.zwVfOhHlH01VGJAW.rnd?partNumber=8&uploadId=b9902c56-fc69-4228-a307-e037bc039629. Retry again.
```
[must-gather-1402_1.tar.gz](https://github.com/noobaa/noobaa-core/files/8058940/must-gather-1402_1.tar.gz)

**Comment by romayalon** [comment]
@akmithal 
According to the logs, it seems that many of the file system operations are being executed very slowly.
(also notice that there are other IOs being executed at the same time which might slow it down too).
I can absolutely see time threshold warnings on Fsync and on FileWrite, according to these warnings I'm suspecting that like @jeniawhite said before, the s3 tool terminates the request, I suspect that it's due to the times issue. 
Also, I'll add that I'm not able to reproduce it on my system, so please provide the exact command you ran.
Thanks.

**Comment by jeniawhite** [comment]
@romayalon 
Notice that previously the connection was closed by the client
But in the latest logs, you see ```Connection closed by foreign host```, which navigates me to think that the endpoint closed the connection
I'm not sure if the problem is the same, in the latest case it looks like NooBaa was the one closing the connection and not the client

**Comment by romayalon** [comment]
@jeniawhite Thanks for your input, I updated my comment accordingly.

**Comment by romayalon** [comment]
@akmithal 
As per our discussion (PVC doesn't contain enough capacity for uploading all the objects according to the running warp command), any updates regarding the reproduction?

**Comment by akmithal** [comment]
Closing this defect as it is not recreatable with build [5.9_nsfsfixes-20220215](https://hub.docker.com/layers/noobaa/noobaa-core/5.9_nsfsfixes-20220215/images/sha256-446d1ab5d795d5aed911c5fdc85a720ec67fd7f1939b4cb9e30b51a02d5acb8d?context=explore)
