### ISSUE TITLE
GMCTP: Spark writes resulting in endpoint Panic (hpo-core 617)

### ISSUE THREAD

**Issue by akmithal** [noobaa/noobaa-core#6926]
### Bug Description
While running Spark TPC-DS testcase, we encountered the following Panic on one of the endpoints that we were tailing the logs for. On this system, we had 5 endpoints for each IP address (scaleFactor=5).  The reads were OK - as they were verified by queries, but when we went to do the first write, the Panic occurred and all 5 endpoints restarted.

**Account that we were running to, the endpoint IP, and the bucket:**
~#  mmdas account list s3user8094 -o json
{
  "access_key" : "8HqJ2BCynSWh6jwS5cGp",
  "gid" : 9004,
  "name" : "s3user8094",
  "newBucketsPath" : "/mnt/remote-fs3k-noobaa/pre-created-export-user-2/",
  "secret_key" : "aM36y+Y+EgfSak1vIYuwdIJvMvWgU3T+Vv300pbs",
  "uid" : 8094
}

IP: 192.100.229.196
Bucket: spark-tpcds

**Logs from pod, noobaa-endpoint-54997d8cf9-zrchm:**
Mar-24 19:33:15.368 [Endpoint/14]    [L0] core.server.system_services.system_store:: SystemStore.load: Got load request with a timestamp older then my last update time
Mar-24 19:33:15.639 [Endpoint/14]    [L0] core.endpoint.s3.ops.s3_put_object:: PUT OBJECT spark-tpcds customer_address.parquet/_temporary/0/
Mar-24 19:33:15.654 [Endpoint/14] [ERROR] core.sdk.namespace_fs:: _upload_stream had error:  Error: Pipeline called on destroyed stream
    at Object.pipeline (/root/node_modules/noobaa-core/src/util/stream_utils.js:36:21)
    at NamespaceFS._upload_stream (/root/node_modules/noobaa-core/src/sdk/namespace_fs.js:780:32)
    at async Semaphore.surround_count (/root/node_modules/noobaa-core/src/util/semaphore.js:90:84)
    at async NamespaceFS.upload_object (/root/node_modules/noobaa-core/src/sdk/namespace_fs.js:639:28)
    at async ObjectSDK.upload_object (/root/node_modules/noobaa-core/src/sdk/object_sdk.js:504:23)
    at async Object.put_object [as handler] (/root/node_modules/noobaa-core/src/endpoint/s3/ops/s3_put_object.js:30:19)
    at async handle_request (/root/node_modules/noobaa-core/src/endpoint/s3/s3_rest.js:149:19)
    at async Object.s3_rest [as handler] (/root/node_modules/noobaa-core/src/endpoint/s3/s3_rest.js:68:9)
Mar-24 19:33:15.655 [Endpoint/14] [ERROR] CONSOLE:: PANIC: process uncaughtException Error: Pipeline called on destroyed stream
    at Object.pipeline (/root/node_modules/noobaa-core/src/util/stream_utils.js:36:21)
    at NamespaceFS._upload_stream (/root/node_modules/noobaa-core/src/sdk/namespace_fs.js:780:32)
    at async Semaphore.surround_count (/root/node_modules/noobaa-core/src/util/semaphore.js:90:84)
    at async NamespaceFS.upload_object (/root/node_modules/noobaa-core/src/sdk/namespace_fs.js:639:28)
    at async ObjectSDK.upload_object (/root/node_modules/noobaa-core/src/sdk/object_sdk.js:504:23)
    at async Object.put_object [as handler] (/root/node_modules/noobaa-core/src/endpoint/s3/ops/s3_put_object.js:30:19)
    at async handle_request (/root/node_modules/noobaa-core/src/endpoint/s3/s3_rest.js:149:19)
    at async Object.s3_rest [as handler] (/root/node_modules/noobaa-core/src/endpoint/s3/s3_rest.js:68:9)

######################################################################
Thu Mar 24 19:33:15 UTC 2022 NooBaa: Process exited RIP (RC=1)
######################################################################

**Here, you can see the 5 endpoints that were affected:**
![image](https://media.github.ibm.com/user/258094/files/6fbff680-ac2d-11ec-8c33-2605dcb3b0fb)

**Here you can see that wordcounts are being executed successfully on some of the tables, but when we go to write our .parquet file, the Spark testcase hangs. Investigating the hang is when we see the endpoints crashing.**
scala> spark.sql("select count (*) from web_returns").show()
+--------+
|count(1)|
+--------+
|   71763|
+--------+

scala> spark.sql("select count (*) from web_sales").show()
+--------+
|count(1)|
+--------+
|  719384|
+--------+

scala> spark.sql("select count (*) from web_site").show()
+--------+
|count(1)|
+--------+
|      30|
+--------+

scala>

scala> CAdf.write.parquet("s3a://spark-tpcds/customer_address.parquet")           ==>Panic occurs, here

**Here are the settings in the conf/spark-defaults.conf file:**
spark.hadoop.fs.s3a.endpoint=http://192.100.229.196
spark.hadoop.fs.s3a.access.key=8HqJ2BCynSWh6jwS5cGp
spark.hadoop.fs.s3a.secret.key=aM36y+Y+EgfSak1vIYuwdIJvMvWgU3T+Vv300pbs
spark.hadoop.fs.s3a.path.style.access=true
spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem
spark.executor.memory 1g
spark.driver.memory 1g
spark.executor.instances 5
spark.driver.instances 5
spark.executor.cores 1
spark.driver.cores 1
spark.cores.max 5

### Your environment
- Build Version:
           ODF: 4.9.4-7
           OCP: 4.9.13
           noobaa:
                INFO[0000] CLI version: 5.9.2
                INFO[0000] noobaa-image: noobaa/noobaa-core:5.9.0
                INFO[0000] operator-image: noobaa/noobaa-operator:5.9.2

- Machine: 
           ClusterID: a47c2ca7-c455-4d67-955d-c8bb390fb803
           ClusterVersion: Stable at "4.9.13"
           ClusterOperators:
               All healthy and stable

### Expected behaviour
The endpoints should stay healthy as this is a very basic Spark testcase and Spark is not consuming a large amount of resource.

### Logs can be found:
https://ibm.ent.box.com/folder/145794528783?s=uueh7fp424vxs2bt4ndrnvh7uusgu6to
1. all.20220325183433.4050707.tar
2. must-gather-GMCTP-Spark.tar.gz

**Comment by akmithal** [comment]
@nimrod-becker , @romayalon FYI

**Comment by romayalon** [comment]
Hi @akmithal ,
Spark is using chunked upload if you won't disable it, we had a bug on chunked upload which looks exactly like the error you provided, https://github.com/noobaa/noobaa-core/pull/6854, this fix was backported to 5.9 branch 7 days ago (https://github.com/noobaa/noobaa-core/pull/6913), according to the last comment in https://github.com/noobaa/noobaa-core/issues/6920 - noobaa/noobaa-core:5.9-20220323 contains the fix.

**Comment by nimrod-becker** [comment]
Fixed with https://github.com/noobaa/noobaa-core/pull/6854
