### ISSUE TITLE
Network issue that looked like Noobaa database is corrupted after hosting node for noobaa-db and noobaa-backing-store powered down 

### ISSUE THREAD

**Issue by MonicaLemay** [noobaa/noobaa-core#6963]
### Environment info
- NooBaa Version: **VERSION**
root@c83f1-infa noobaa_db_corrupt]# noobaa status
INFO[0000] CLI version: 5.9.2
INFO[0000] noobaa-image: quay.io/rhceph-dev/odf4-mcg-core-rhel8@sha256:03f043cea8c01e91b46b9df89f98a13c18794d5821c8fe408343046121772639
INFO[0000] operator-image: quay.io/rhceph-dev/odf4-mcg-rhel8-operator@sha256:3b5f147bee2feff5b8805ef26cf327fa265738fbcc74a97dbdbce6735badb262
INFO[0000] noobaa-db-image: quay.io/rhceph-dev/rhel8-postgresql-12@sha256:fa920188f567e51d75aacd723f0964026e42ac060fed392036e8d4b3c7a8129f
root@c83f1-infa noobaa_db_corrupt]# noobaa version
INFO[0000] CLI version: 5.9.2
INFO[0000] noobaa-image: noobaa/noobaa-core:5.9.0
INFO[0000] operator-image: noobaa/noobaa-operator:5.9.2
[root@c83f1-infa noobaa_db_corrupt]#

ODF 4.9.7-2
OCP 4.9.31

- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify**

### Actual behavior
The scale factor is set to 12 so there are 36 endpoint pods.

A warp workload is running to only one of the three worker nodes.  It is doing mixed I/O (read/write/delete with size 3G
```
./warp mixed --host=172.20.100.22 --host-select=roundrobin --access-key=o3p0HCwfigaJViNCZkAj --secret-key=AukwT/qp10hu/QAT2k1tUOfpeeQIYxdmHwBDoEml --obj.size=3G --duration=5h --bucket=s5001b1 --debug  --insecure  --tls --benchdata=/home/RW_moki/warp --warp-client=10.28.20.26,10.28.20.28,10.28,20,27 --obj.randsize --objects=1000 --concurrent=20 
```

While I/O is running, I am also doing s3 mb command using the IP of a different worker node
```
Also  for I in {5..500}
do
s5001_3 mb s3://s5001b${I} done 
```
Additionally, I am creating new accounts using a command from the OCP Infrastructure node to create accounts
```
for I in {5..500}
> do
>  account create s500${I}  
> done

```
On worker node1, also called dan1, both the noobaa-db and the noobaa-backing-store pods are running
```
noobaa-db-pg-0                                     1/1     Running   0          51m     10.128.4.241   c83f1-dan1.ocp4.pokprv.stglabs.ibm.com   <none>           <none>
noobaa-default-backing-store-noobaa-pod-24af9c5b   1/1     Running   0          51m     10.128.4.244   c83f1-dan1.ocp4.pokprv.stglabs.ibm.com   <none>           <none>
```

Once I/O and s3 mb and account create are running, I power off the worker node1 (dan1)
```
[root@c83f1-infa ~]# date; ipmitool -I lanplus -H 10.28.16.145 -U USERID -P Hp00cpcluster power off; date
Thu May 19 17:44:52 EDT 2022
Chassis Power Control: Down/Off
Thu May 19 17:44:52 EDT 2022
[root@c83f1-infa ~]#

```

After the power down, the I/O workload from warp reports:
```
I/O warp clients report intermittent failures warp: Sending benchmark_status
warp: <ERROR> upload error: We encountered an internal error. Please try again.
warp: <ERROR> upload error: We encountered an internal error. Please try again.
warp: Request: stage_status
warp: Sending benchmark_status
warp: Request: stage_status
warp: Sending benchmark_status
warp: Request: stage_status
warp: Sending benchmark_status
warp: <ERROR> upload error: We encountered an internal error. Please try again.

```
And the endpoint pods correctly report:
```
  oc logs -f deployment/noobaa-endpoint --all-containers=true --prefix=true --max-log-requests=40 --since=15m | grep -i error | grep s5001b1

pod/noobaa-endpoint-7977c586cf-vk95l/endpoint] May-19 21:44:54.025 [Endpoint/14] [ERROR] core.util.postgres_client:: got error on postgres pool error: terminating connection due to administrator command
[pod/noobaa-endpoint-7977c586cf-vk95l/endpoint] May-19 21:45:39.071 [Endpoint/14] [ERROR] core.util.postgres_client:: findOneAndUpdate failed { start_time: 1652996400000, end_time: 1652996999999, system: 62866e565b8cf90029ebe9af, group_name: '3b9d1d25-2fd4-473b-a95f-4d9b0337c757' } {
[pod/noobaa-endpoint-7977c586cf-vk95l/endpoint] } { upsert: true, returnOriginal: false } Error: connect EHOSTUNREACH 10.128.4.241:5432
[pod/noobaa-endpoint-7977c586cf-vk95l/endpoint] May-19 21:45:39.072 [Endpoint/14] [ERROR] CONSOLE:: RPC._on_request: ERROR srv object_api.add_endpoint_report reqid 870@fcall://fcall(7oeqsw2y) connid fcall://fcall(7oeqsw2y) TypeError: Cannot read property 'release' of undefined
[pod/noobaa-endpoint-7977c586cf-vk95l/endpoint] May-19 21:45:39.073 [Endpoint/14] [ERROR] core.util.postgres_client:: findOneAndUpdate failed { system: 62866e565b8cf90029ebe9af } { '$inc': { 's3_usage_info.total_calls': 0, 's3_errors_info.total_errors': 0 } } { upsert: true, returnOriginal: false } Error: connect EHOSTUNREACH 10.128.4.241:5432

```
All of that above is correct and not of concern.  I/O recovers in less than a minute and all is good with the warp I/O.

What is of concern is that anything writing to the noobaa database hangs.
```
make_bucket failed: s3://s5001b13 Read timeout on endpoint URL: "http://172.20.100.23/s5001b13"

``` 

Also of concern is that the "account create" fails 
```
Something went wrong while processing the request.
Check  logs  for more details
```

I have run this test many times and have never seen the noobaa db get corrupted.  The last time I ran this, I had ODF 4.9.6 and the noobaa patch 
```
noobaa/noobaa-core:moki-20220511
```
At this time I only have noobaa-4.9.7-2 and no patches.

In the past, I would see the above mentioned errors but after a few minutes the failover would occur of the db pod and the s3 comomand and account create commands would recover and contnue.  They did not this time.

The pods are back online and "Running"

```
Every 2.0s: oc get pods                             c83f1-infa: Thu May 19 18:10:07 2022

NAME                                               READY   STATUS        RESTARTS      A
GE
noobaa-core-0                                      1/1     Running	 0             5
h50m
noobaa-db-pg-0                                     1/1     Running       0             2
3m
noobaa-default-backing-store-noobaa-pod-24af9c5b   1/1     Running       0             1
```

However, the commands s3 commands still hang.

I waited over 20 minutes and powered the node back on.  

```
[root@c83f1-infa ~]# date; ipmitool -I lanplus -H 10.28.16.145 -U USERID -P Hp00cpcluster power on; date
Thu May 19 18:11:41 EDT 2022
Chassis Power Control: Up/On
Thu May 19 18:11:41 EDT 2022
[root@c83f1-infa ~]#
```

The database is still offline.  It appears to be corrupted.

```
[root@c83f1-infa ~]# noobaa api account_api list_accounts '{}' | grep email
INFO[0000] ✅ Exists: NooBaa "noobaa"
INFO[0000] ✅ Exists: Service "noobaa-mgmt"
INFO[0000] ✅ Exists: Secret "noobaa-operator"
INFO[0000] ✅ Exists: Secret "noobaa-admin"
INFO[0000] ✈️  RPC: account.list_accounts() Request: map[]
WARN[0000] RPC: GetConnection creating connection to wss://localhost:33035/rpc/ 0xc000de7a40
INFO[0000] RPC: Connecting websocket (0xc000de7a40) &{RPC:0xc0001df950 Address:wss://localhost:33035/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s cancelPings:<nil>}
INFO[0000] RPC: Connected websocket (0xc000de7a40) &{RPC:0xc0001df950 Address:wss://localhost:33035/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s cancelPings:<nil>}
INFO[0005] RPC: Ping (0xc000de7a40) &{RPC:0xc0001df950 Address:wss://localhost:33035/rpc/ State:connected WS:0xc0014d61c0 PendingRequests:map[wss://localhost:33035/rpc/-0:0xc0007261b0] NextRequestID:1 Lock:{state:0 sema:0} ReconnectDelay:0s cancelPings:0x63b440}
```

the noobaa-core pod log shows:
```
^[[32mMay-20 17:26:28.648^[[35m [WebServer/41] ^[[31m[ERROR]^[[39m core.rpc.rpc:: RPC._request: response ERROR srv agent_api.test_network_perf reqid 5@n2n://62866f2b5b8cf90029ebe9ca(vzorwifk1) connid n2n://62866f2b5b8cf90029ebe9ca(vzorwifk1) params { source: ^[[32m'n2n://nodes_monitor'^[[39m, target: ^[[32m'n2n://62866f2b5b8cf90029ebe9ca'^[[39m, response_length: ^[[33m1^[[39m }  Error: RPC CONNECT TIMEOUT
    at Timeout._onTimeout (/root/node_modules/noobaa-core/src/rpc/rpc_base_conn.js:120:43)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
(node:41) UnhandledPromiseRejectionWarning: Error: RPC CONNECT TIMEOUT
    at Timeout._onTimeout (/root/node_modules/noobaa-core/src/rpc/rpc_base_conn.js:120:43)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
(node:41) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3324)
(node:41) UnhandledPromiseRejectionWarning: Error: RPC CONNECT TIMEOUT
    at Timeout._onTimeout (/root/node_modules/noobaa-core/src/rpc/rpc_base_conn.js:120:43)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
(node:41) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3325)

```

and noobaa commands had timeout
```
noobaa api bucket_api list_buckets and noobaa api account_api list_accounts '{}' are all timeouted

```

We are holding the cluster in this state in case you want to investigate it while it is in this condition.

### Expected behavior
A node outage while actively writing to database should not result in db corruption.

### Steps to reproduce
Steps and enviroment are all listed abo e

### More information - Screenshots / Logs / Other output
Logs are in
https://ibm.ent.box.com/folder/145794528783?s=uueh7fp424vxs2bt4ndrnvh7uusgu6tocd

**Comment by guymguym** [comment]
@MonicaLemay What do the db pod logs say?

**Comment by cxhong** [comment]
db log: 
```
# oc logs noobaa-db-pg-0
pg_ctl: another server might be running; trying to start server anyway
waiting for server to start....2022-05-19 21:52:21.900 UTC [23] LOG:  starting PostgreSQL 12.9 on x86_64-redhat-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-4), 64-bit
2022-05-19 21:52:21.902 UTC [23] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2022-05-19 21:52:21.904 UTC [23] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2022-05-19 21:52:22.026 UTC [23] LOG:  redirecting log output to logging collector process
2022-05-19 21:52:22.026 UTC [23] HINT:  Future log output will appear in directory "log".
... done
server started
/var/run/postgresql:5432 - accepting connections
=> sourcing /usr/share/container-scripts/postgresql/start/set_passwords.sh ...
ALTER ROLE
waiting for server to shut down.... done
server stopped
Starting server...
2022-05-19 21:52:25.306 UTC [1] LOG:  starting PostgreSQL 12.9 on x86_64-redhat-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-4), 64-bit
2022-05-19 21:52:25.306 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2022-05-19 21:52:25.306 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2022-05-19 21:52:25.308 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2022-05-19 21:52:25.310 UTC [1] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2022-05-19 21:52:25.384 UTC [1] LOG:  redirecting log output to logging collector process
2022-05-19 21:52:25.384 UTC [1] HINT:  Future log output will appear in directory "log".
```
I can get to noobaa-db pod, and run the pgsql commands.  looks like all the Data(account/exports) are all still available

**Comment by akmithal** [comment]
Hi @nimrod-becker , @guymguym , @romayalon : The setup details are shared on slack message by @MonicaLemay , so please use it if needed. Thanks

**Comment by MonicaLemay** [comment]
db pod logs output 
```
pg_ctl: another server might be running; trying to start server anyway
waiting for server to start....2022-05-19 21:52:21.900 UTC [23] LOG:  starting PostgreSQL 12.9 on x86_64-redhat-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-4), 64-bit
2022-05-19 21:52:21.902 UTC [23] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2022-05-19 21:52:21.904 UTC [23] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2022-05-19 21:52:22.026 UTC [23] LOG:  redirecting log output to logging collector process
2022-05-19 21:52:22.026 UTC [23] HINT:  Future log output will appear in directory "log".
... done
server started
/var/run/postgresql:5432 - accepting connections
=> sourcing /usr/share/container-scripts/postgresql/start/set_passwords.sh ...
ALTER ROLE
waiting for server to shut down.... done
server stopped
Starting server...
2022-05-19 21:52:25.306 UTC [1] LOG:  starting PostgreSQL 12.9 on x86_64-redhat-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-4), 64-bit
2022-05-19 21:52:25.306 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2022-05-19 21:52:25.306 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2022-05-19 21:52:25.308 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2022-05-19 21:52:25.310 UTC [1] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2022-05-19 21:52:25.384 UTC [1] LOG:  redirecting log output to logging collector process
2022-05-19 21:52:25.384 UTC [1] HINT:  Future log output will appear in directory "log".
```

**Comment by MonicaLemay** [comment]
We rebooted the worker node 1 and deleted all noobaa pods.  After that everything worked fine.  At this time, I don't think this is a noobaa problem but looks like it migh have been a network problem.  I will test on another cluster just to make sure.

**Comment by romayalon** [comment]
@MonicaLemay Can you please also change the headline of this defect to a networking issue after node shutdown or something similar?
As we discussed on slack,  it's not a DB corruption - the noobaa-core pod logs show successful db queries, and Monica rshed to the db pod and saw her data there.
From the logs, we see RPC connection issues that are probably caused due to the networking problem.

**Comment by MonicaLemay** [comment]
I am going to close this.  It is not a bug w/ noobaa but a network issue

**Comment by rkomandu** [comment]
@MonicaLemay , please describe what type of network issue is related to this one in our slack channel for better understanding

**Comment by MonicaLemay** [comment]
It is a problem that is unique to this one test stand.  The data network is bonded.  There is bond0 and bond1.  Randomly, bond0 and or bond1 goes down and it causes problems with the cluster.  The bonds have to be manually restored.  I tested the scenario 2 more times.  One on the original test stand when the bond0 and bond1 was up and on anohter test stand that does not have this unique odd problem.  Both times I could not get a recreate.
