### ISSUE TITLE
Create table on Hive stalls

### ISSUE THREAD

**Issue by zzenonn** [noobaa/noobaa-core#7037]
### Environment info
- NooBaa Version: **noobaa/noobaa-core:5.10.1** **noobaa/noobaa-operator:5.10.1**
- Platform: **EKS 1.21**

### Actual behavior
1. CREATE TABLE statement fails
2. No error is displayed, but command does not finish running

### Expected behavior
1. Table should be created

### Steps to reproduce
1. Run `beeline -u jdbc:hive2://$(curl 169.254.169.254/latest/meta-data/local-ipv4):10000/ -n hadoop`
2. Run a create table script. The command used in this case was:
```sql
CREATE EXTERNAL TABLE `ursa_labs_taxi_data`(
  `vendor_id` string, 
  `pickup_at` timestamp, 
  `dropoff_at` timestamp, 
  `passenger_count` tinyint, 
  `trip_distance` float, 
  `pickup_longitude` float, 
  `pickup_latitude` float, 
  `rate_code_id` string, 
  `store_and_fwd_flag` string, 
  `dropoff_longitude` float, 
  `dropoff_latitude` float, 
  `payment_type` string, 
  `fare_amount` float, 
  `extra` float, 
  `mta_tax` float, 
  `tip_amount` float, 
  `tolls_amount` float, 
  `total_amount` float, 
  `improvement_surcharge` float, 
  `pickup_location_id` int, 
  `dropoff_location_id` int, 
  `congestion_surcharge` float)
PARTITIONED BY ( 
  `year` int, 
  `month` int)
ROW FORMAT SERDE 
  'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe' 
STORED AS INPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat' 
OUTPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'
LOCATION
  's3a://ursa-labs-taxi-data/';
```

### More information - Screenshots / Logs / Other output
The s3a connector was used. Here are the logs for the task.
```
2022-08-09T07:26:29,729 WARN  [bc39319f-c457-44e1-83a9-9deb8004bfd7 HiveServer2-Handler-Pool: Thread-44([])]: common.FileUtils (FileUtils.java:isLocalFile(521)) - Unable to get FileSystem for s3a://ursa-labs-taxi-data/
org.apache.hadoop.fs.s3a.AWSClientIOException: doesBucketExist on ursa-labs-taxi-data: com.amazonaws.SdkClientException: Unable to execute HTTP request: ursa-labs-taxi-data.ac308bca636534f5cb39deba9b0b6631-393073014.ap-southeast-1.elb.amazonaws.com: Unable to execute HTTP request: ursa-labs-taxi-data.ac308bca636534f5cb39deba9b0b6631-393073014.ap-southeast-1.elb.amazonaws.com
	at org.apache.hadoop.fs.s3a.S3AUtils.translateException(S3AUtils.java:189) ~[hadoop-aws-3.2.1-amzn-7.jar:?]
	at org.apache.hadoop.fs.s3a.Invoker.once(Invoker.java:111) ~[hadoop-aws-3.2.1-amzn-7.jar:?]
	at org.apache.hadoop.fs.s3a.Invoker.lambda$retry$3(Invoker.java:265) ~[hadoop-aws-3.2.1-amzn-7.jar:?]
	at org.apache.hadoop.fs.s3a.Invoker.retryUntranslated(Invoker.java:322) ~[hadoop-aws-3.2.1-amzn-7.jar:?]
	at org.apache.hadoop.fs.s3a.Invoker.retry(Invoker.java:261) ~[hadoop-aws-3.2.1-amzn-7.jar:?]
	at org.apache.hadoop.fs.s3a.Invoker.retry(Invoker.java:236) ~[hadoop-aws-3.2.1-amzn-7.jar:?]
	at org.apache.hadoop.fs.s3a.S3AFileSystem.verifyBucketExists(S3AFileSystem.java:379) ~[hadoop-aws-3.2.1-amzn-7.jar:?]
	at org.apache.hadoop.fs.s3a.S3AFileSystem.initialize(S3AFileSystem.java:313) ~[hadoop-aws-3.2.1-amzn-7.jar:?]
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3364) ~[hadoop-common-3.2.1-amzn-7.jar:?]
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:123) ~[hadoop-common-3.2.1-amzn-7.jar:?]
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3413) ~[hadoop-common-3.2.1-amzn-7.jar:?]
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3381) ~[hadoop-common-3.2.1-amzn-7.jar:?]
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:486) ~[hadoop-common-3.2.1-amzn-7.jar:?]
	at org.apache.hadoop.hive.common.FileUtils.isLocalFile(FileUtils.java:518) [hive-common-3.1.3-amzn-0.jar:3.1.3-amzn-0]
	at org.apache.hadoop.hive.ql.parse.BaseSemanticAnalyzer.toReadEntity(BaseSemanticAnalyzer.java:2146) [hive-exec-3.1.3-amzn-0.jar:3.1.3-amzn-0]
	at org.apache.hadoop.hive.ql.parse.BaseSemanticAnalyzer.toReadEntity(BaseSemanticAnalyzer.java:2140) [hive-exec-3.1.3-amzn-0.jar:3.1.3-amzn-0]
	at org.apache.hadoop.hive.ql.parse.BaseSemanticAnalyzer.toReadEntity(BaseSemanticAnalyzer.java:2136) [hive-exec-3.1.3-amzn-0.jar:3.1.3-amzn-0]
	at org.apache.hadoop.hive.ql.parse.SemanticAnalyzer.analyzeCreateTable(SemanticAnalyzer.java:13264) [hive-exec-3.1.3-amzn-0.jar:3.1.3-amzn-0]
	at org.apache.hadoop.hive.ql.parse.SemanticAnalyzer.genResolvedParseTree(SemanticAnalyzer.java:12115) [hive-exec-3.1.3-amzn-0.jar:3.1.3-amzn-0]
	at org.apache.hadoop.hive.ql.parse.SemanticAnalyzer.analyzeInternal(SemanticAnalyzer.java:12268) [hive-exec-3.1.3-amzn-0.jar:3.1.3-amzn-0]
	at org.apache.hadoop.hive.ql.parse.CalcitePlanner.analyzeInternal(CalcitePlanner.java:364) [hive-exec-3.1.3-amzn-0.jar:3.1.3-amzn-0]
	at org.apache.hadoop.hive.ql.parse.BaseSemanticAnalyzer.analyze(BaseSemanticAnalyzer.java:294) [hive-exec-3.1.3-amzn-0.jar:3.1.3-amzn-0]
	at org.apache.hadoop.hive.ql.Driver.compile(Driver.java:669) [hive-exec-3.1.3-amzn-0.jar:3.1.3-amzn-0]
	at org.apache.hadoop.hive.ql.Driver.compileInternal(Driver.java:1844) [hive-exec-3.1.3-amzn-0.jar:3.1.3-amzn-0]
	at org.apache.hadoop.hive.ql.Driver.compileAndRespond(Driver.java:1791) [hive-exec-3.1.3-amzn-0.jar:3.1.3-amzn-0]
	at org.apache.hadoop.hive.ql.Driver.compileAndRespond(Driver.java:1786) [hive-exec-3.1.3-amzn-0.jar:3.1.3-amzn-0]
	at org.apache.hadoop.hive.ql.reexec.ReExecDriver.compileAndRespond(ReExecDriver.java:126) [hive-exec-3.1.3-amzn-0.jar:3.1.3-amzn-0]
	at org.apache.hive.service.cli.operation.SQLOperation.prepare(SQLOperation.java:196) [hive-service-3.1.3-amzn-0.jar:3.1.3-amzn-0]
	at org.apache.hive.service.cli.operation.SQLOperation.runInternal(SQLOperation.java:261) [hive-service-3.1.3-amzn-0.jar:3.1.3-amzn-0]
	at org.apache.hive.service.cli.operation.Operation.run(Operation.java:260) [hive-service-3.1.3-amzn-0.jar:3.1.3-amzn-0]
	at org.apache.hive.service.cli.session.HiveSessionImpl.executeStatementInternal(HiveSessionImpl.java:559) [hive-service-3.1.3-amzn-0.jar:3.1.3-amzn-0]
	at org.apache.hive.service.cli.session.HiveSessionImpl.executeStatementAsync(HiveSessionImpl.java:545) [hive-service-3.1.3-amzn-0.jar:3.1.3-amzn-0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_342]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_342]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_342]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_342]
	at org.apache.hive.service.cli.session.HiveSessionProxy.invoke(HiveSessionProxy.java:78) [hive-service-3.1.3-amzn-0.jar:3.1.3-amzn-0]
	at org.apache.hive.service.cli.session.HiveSessionProxy.access$000(HiveSessionProxy.java:36) [hive-service-3.1.3-amzn-0.jar:3.1.3-amzn-0]
	at org.apache.hive.service.cli.session.HiveSessionProxy$1.run(HiveSessionProxy.java:63) [hive-service-3.1.3-amzn-0.jar:3.1.3-amzn-0]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_342]
	at javax.security.auth.Subject.doAs(Subject.java:422) [?:1.8.0_342]
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730) [hadoop-common-3.2.1-amzn-7.jar:?]
	at org.apache.hive.service.cli.session.HiveSessionProxy.invoke(HiveSessionProxy.java:59) [hive-service-3.1.3-amzn-0.jar:3.1.3-amzn-0]
	at com.sun.proxy.$Proxy40.executeStatementAsync(Unknown Source) [?:?]
	at org.apache.hive.service.cli.CLIService.executeStatementAsync(CLIService.java:315) [hive-service-3.1.3-amzn-0.jar:3.1.3-amzn-0]
	at org.apache.hive.service.cli.thrift.ThriftCLIService.ExecuteStatement(ThriftCLIService.java:566) [hive-service-3.1.3-amzn-0.jar:3.1.3-amzn-0]
	at org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement.getResult(TCLIService.java:1557) [hive-exec-3.1.3-amzn-0.jar:3.1.3-amzn-0]
	at org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement.getResult(TCLIService.java:1542) [hive-exec-3.1.3-amzn-0.jar:3.1.3-amzn-0]
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39) [hive-exec-3.1.3-amzn-0.jar:3.1.3-amzn-0]
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39) [hive-exec-3.1.3-amzn-0.jar:3.1.3-amzn-0]
	at org.apache.hive.service.auth.TSetIpAddressProcessor.process(TSetIpAddressProcessor.java:56) [hive-service-3.1.3-amzn-0.jar:3.1.3-amzn-0]
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:286) [hive-exec-3.1.3-amzn-0.jar:3.1.3-amzn-0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_342]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_342]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_342]
Caused by: com.amazonaws.SdkClientException: Unable to execute HTTP request: ursa-labs-taxi-data.ac308bca636534f5cb39deba9b0b6631-393073014.ap-southeast-1.elb.amazonaws.com
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1216) ~[aws-java-sdk-bundle-1.12.170.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1162) ~[aws-java-sdk-bundle-1.12.170.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:811) ~[aws-java-sdk-bundle-1.12.170.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:779) ~[aws-java-sdk-bundle-1.12.170.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:753) ~[aws-java-sdk-bundle-1.12.170.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:713) ~[aws-java-sdk-bundle-1.12.170.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:695) ~[aws-java-sdk-bundle-1.12.170.jar:?]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:559) ~[aws-java-sdk-bundle-1.12.170.jar:?]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:539) ~[aws-java-sdk-bundle-1.12.170.jar:?]
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5453) ~[aws-java-sdk-bundle-1.12.170.jar:?]
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5400) ~[aws-java-sdk-bundle-1.12.170.jar:?]
	at com.amazonaws.services.s3.AmazonS3Client.headBucket(AmazonS3Client.java:1450) ~[aws-java-sdk-bundle-1.12.170.jar:?]
	at com.amazonaws.services.s3.AmazonS3Client.doesBucketExist(AmazonS3Client.java:1386) ~[aws-java-sdk-bundle-1.12.170.jar:?]
	at org.apache.hadoop.fs.s3a.S3AFileSystem.lambda$verifyBucketExists$1(S3AFileSystem.java:380) ~[hadoop-aws-3.2.1-amzn-7.jar:?]
	at org.apache.hadoop.fs.s3a.Invoker.once(Invoker.java:109) ~[hadoop-aws-3.2.1-amzn-7.jar:?]
	... 53 more
Caused by: java.net.UnknownHostException: ursa-labs-taxi-data.ac308bca636534f5cb39deba9b0b6631-393073014.ap-southeast-1.elb.amazonaws.com
	at java.net.InetAddress.getAllByName0(InetAddress.java:1287) ~[?:1.8.0_342]
	at java.net.InetAddress.getAllByName(InetAddress.java:1199) ~[?:1.8.0_342]
	at java.net.InetAddress.getAllByName(InetAddress.java:1127) ~[?:1.8.0_342]
	at com.amazonaws.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:27) ~[aws-java-sdk-bundle-1.12.170.jar:?]
	at com.amazonaws.http.DelegatingDnsResolver.resolve(DelegatingDnsResolver.java:38) ~[aws-java-sdk-bundle-1.12.170.jar:?]
	at com.amazonaws.thirdparty.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112) ~[aws-java-sdk-bundle-1.12.170.jar:?]
	at com.amazonaws.thirdparty.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376) ~[aws-java-sdk-bundle-1.12.170.jar:?]
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_342]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_342]
	at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76) ~[aws-java-sdk-bundle-1.12.170.jar:?]
	at com.amazonaws.http.conn.$Proxy43.connect(Unknown Source) ~[?:?]
	at com.amazonaws.thirdparty.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) ~[aws-java-sdk-bundle-1.12.170.jar:?]
	at com.amazonaws.thirdparty.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[aws-java-sdk-bundle-1.12.170.jar:?]
	at com.amazonaws.thirdparty.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[aws-java-sdk-bundle-1.12.170.jar:?]
	at com.amazonaws.thirdparty.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[aws-java-sdk-bundle-1.12.170.jar:?]
	at com.amazonaws.thirdparty.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[aws-java-sdk-bundle-1.12.170.jar:?]
	at com.amazonaws.thirdparty.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) ~[aws-java-sdk-bundle-1.12.170.jar:?]
	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72) ~[aws-java-sdk-bundle-1.12.170.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1343) ~[aws-java-sdk-bundle-1.12.170.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1154) ~[aws-java-sdk-bundle-1.12.170.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:811) ~[aws-java-sdk-bundle-1.12.170.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:779) ~[aws-java-sdk-bundle-1.12.170.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:753) ~[aws-java-sdk-bundle-1.12.170.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:713) ~[aws-java-sdk-bundle-1.12.170.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:695) ~[aws-java-sdk-bundle-1.12.170.jar:?]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:559) ~[aws-java-sdk-bundle-1.12.170.jar:?]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:539) ~[aws-java-sdk-bundle-1.12.170.jar:?]
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5453) ~[aws-java-sdk-bundle-1.12.170.jar:?]
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5400) ~[aws-java-sdk-bundle-1.12.170.jar:?]
	at com.amazonaws.services.s3.AmazonS3Client.headBucket(AmazonS3Client.java:1450) ~[aws-java-sdk-bundle-1.12.170.jar:?]
	at com.amazonaws.services.s3.AmazonS3Client.doesBucketExist(AmazonS3Client.java:1386) ~[aws-java-sdk-bundle-1.12.170.jar:?]
	at org.apache.hadoop.fs.s3a.S3AFileSystem.lambda$verifyBucketExists$1(S3AFileSystem.java:380) ~[hadoop-aws-3.2.1-amzn-7.jar:?]
	at org.apache.hadoop.fs.s3a.Invoker.once(Invoker.java:109) ~[hadoop-aws-3.2.1-amzn-7.jar:?]
	... 53 more
2022-08-09T07:26:29,763 INFO  [bc39319f-c457-44e1-83a9-9deb8004bfd7 HiveServer2-Handler-Pool: Thread-44([])]: ql.Driver (Driver.java:compile(676)) - Semantic Analysis Completed (retrial = false)
2022-08-09T07:26:29,769 INFO  [bc39319f-c457-44e1-83a9-9deb8004bfd7 HiveServer2-Handler-Pool: Thread-44([])]: ql.Driver (Driver.java:getSchema(374)) - Returning Hive schema: Schema(fieldSchemas:null, properties:null)
2022-08-09T07:26:29,801 INFO  [bc39319f-c457-44e1-83a9-9deb8004bfd7 HiveServer2-Handler-Pool: Thread-44([])]: ql.Driver (Driver.java:compile(725)) - EXPLAIN output for queryid hive_20220809070524_adddc944-f58d-48d7-b5e1-f6b1d681e68e : STAGE DEPENDENCIES:
  Stage-0 is a root stage [DDL]
```

**Comment by zzenonn** [comment]
I found the issue. There are two:
1. SSL. If you're using a self signed certificate, s3a will error. `fs.s3a.connection.ssl.enabled` should be set to false.
2. By default, s3a uses virtual hosting access (bucket.s3....). Switching it to path access by setting `fs.s3a.path.style.access` to true fixes the issue.
