### ISSUE TITLE
Unable to perform any operations on Noobaa Object Storage: Cannot read property 'exec_account' of undefined

### ISSUE THREAD

**Issue by Harshit-9398** [noobaa/noobaa-core#7054]
Hello,
For past 1 week, we are unable to perform any operations on the Noobaa Object Storage except listing the existing buckets and their content.
When we try to use the Noobaa console, we see the error `Cannot read property 'exec_account' of undefined` in the logs of Noobaa Endpoint pod.

**Environment Details**
OpenShift Cluster v4.8.36
OCS operator v4.8.14

The Block Storage on the same OCS cluster is working fine.
Can you please help us to fix this issue?

**Comment by liranmauda** [comment]
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2120643

**Comment by liranmauda** [comment]
From #7069 :

### Environment info
- NooBaa Version: 5.8
- Platform: OCP 4.8

### Actual behavior
1. read system failed with
```
Aug-18 4:21:51.022 [WebServer/34] [ERROR] CONSOLE:: RPC._on_request: ERROR srv system_api.read_system reqid wss://noobaa-mgmt.openshift-storage.svc.cluster.local:443/rpc/-1059722 connid ws://[::ffff:10.128.3.139]:48262/(31933lxs0) TypeError: Cannot read property 'exec_account' of undefined
    at /root/node_modules/noobaa-core/src/server/system_services/bucket_server.js:1498:69
    at arrayMap (/root/node_modules/noobaa-core/node_modules/lodash/lodash.js:653:23)
    at Function.map (/root/node_modules/noobaa-core/node_modules/lodash/lodash.js:9622:14)
    at Object.get_bucket_info (/root/node_modules/noobaa-core/src/server/system_services/bucket_server.js:1491:23)
    at /root/node_modules/noobaa-core/src/server/system_services/system_server.js:593:39
    at Array.map (<anonymous>)
    at Object.read_system (/root/node_modules/noobaa-core/src/server/system_services/system_server.js:588:93)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /root/node_modules/noobaa-core/src/rpc/rpc.js:340:32
```

The system itself had both functions and triggers enabled.
Once deleted, the system returned to function. 



### Expected behavior
1. Using functions and triggers should not break read system

### Steps to reproduce
1. Unknown

### More information - Screenshots / Logs / Other output
