### ISSUE TITLE
vacuumAndAnalyze runs also in standalone mode when there's no DB connection

### ISSUE THREAD

**Issue by guymguym** [noobaa/noobaa-core#7245]
### Environment info
- NooBaa Version: **VERSION**
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify**

### Actual behavior
1. See here - whenever we initialize the collections we also set a daily interval to call vacuumAndAnalyze

https://github.com/noobaa/noobaa-core/blob/2e5c6dbf90496f91e4718ddfe13ad3d154f56b4b/src/util/postgres_client.js#L605-L610

2. This fails where we run a long running standalone process that has no DB.

### Expected behavior
1. We shouldn't call DB functions if we are not connected to the DB.
2. Specifically for vacuumAndAnalyze the TODO in the code says that it should run in the DB itself - maybe that's a good idea.

### Steps to reproduce
1. Run nsfs standalone for 1 day or more.

### More information - Screenshots / Logs / Other output

<details>
  <summary>Details of error stacktrace</summary>

```
Mar-16 9:55:28.347 [Endpoint/1628356] [ERROR] core.util.postgres_client:: postgres_client: T00000000|Q00000001: failed with error: TypeError: Cannot read properties of undefined (reading ‘query
’)
    at _do_query (/snapshot/noobaa-core/src/util/postgres_client.js:249:37)
    at PostgresTable.single_query (/snapshot/noobaa-core/src/util/postgres_client.js:678:16)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:533:9)
    at process.processTimers (node:internal/timers:507:7)
    at async Timeout.vacuumAndAnalyze [as _onTimeout] (/snapshot/noobaa-core/src/util/postgres_client.js:699:13)
Mar-16 9:55:28.347 [Endpoint/1628356] [ERROR] core.util.postgres_client:: vacuumAndAnalyze failed TypeError: Cannot read properties of undefined (reading ‘query’)
    at _do_query (/snapshot/noobaa-core/src/util/postgres_client.js:249:37)
    at PostgresTable.single_query (/snapshot/noobaa-core/src/util/postgres_client.js:678:16)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:533:9)
    at process.processTimers (node:internal/timers:507:7)
    at async Timeout.vacuumAndAnalyze [as _onTimeout] (/snapshot/noobaa-core/src/util/postgres_client.js:699:13)
Mar-16 9:55:28.348 [Endpoint/1628356] [ERROR] CONSOLE:: PANIC: process uncaughtException TypeError: Cannot read properties of undefined (reading ‘query’)
    at _do_query (/snapshot/noobaa-core/src/util/postgres_client.js:249:37)
    at PostgresTable.single_query (/snapshot/noobaa-core/src/util/postgres_client.js:678:16)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:533:9)
    at process.processTimers (node:internal/timers:507:7)
    at async Timeout.vacuumAndAnalyze [as _onTimeout] (/snapshot/noobaa-core/src/util/postgres_client.js:699:13)

```

</details>

**Comment by guymguym** [comment]
fixed in #7296 - by adding the option to set DB_TYPE=none for nsfs standalone command.
