### ISSUE TITLE
PANIC: process uncaughtException Error: retry update after advisory lock release iostats

### ISSUE THREAD

**Issue by guymguym** [noobaa/noobaa-core#7259]
### Environment info
- NooBaa Version: **VERSION**
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify**

### Actual behavior
1. web server crashes
```
Apr-3 18:38:38.008 [WebServer/797197] [ERROR] core.util.postgres_client:: findOneAndUpdate failed { system: 642a9d052383132854a9f199, resource_id: 642a9dff7f1b5a2a19edd252, resource_type: 'NODE', start_time: 1680447600000, end_time: 180533999999 } { '$set': { system: 642a9d052383132854a9f199, resource_id: 642a9dff7f1b5a2a19edd252, resource_type: 'NODE', start_time: 1680447600000, end_time: 1680533999999 }, '$inc': { read_count: 8, write_count: 8, read_bytes: 8192, write_bytes: 8192, error_read_count: 0, error_write_count: 0, error_read_bytes: 0, error_write_bytes: 0 } } { upsert: true, returnOriginal: false } Error: retry update after advisory lock release iostats
    at PostgresTable._upsert (noobaa-core/src/util/postgres_client.js:1239:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async IoStatsStore._update_io_stats (noobaa-core/src/server/analytic_services/io_stats_store.js:62:21)
    at async IoStatsStore.update_node_io_stats (noobaa-core/src/server/analytic_services/io_stats_store.js:31:9) {
  retry: true
}

Apr-3 18:38:38.008 [WebServer/797197] [ERROR] CONSOLE:: PANIC: process uncaughtException Error: retry update after advisory lock release iostats
    at PostgresTable._upsert (noobaa-core/src/util/postgres_client.js:1239:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async IoStatsStore._update_io_stats (noobaa-core/src/server/analytic_services/io_stats_store.js:62:21)
    at async IoStatsStore.update_node_io_stats (noobaa-core/src/server/analytic_services/io_stats_store.js:31:9)
```

### Expected behavior
1. no uncaught exceptions

### Steps to reproduce
1. using backingstores with erasure coding and occasionally it fails like so (when updating stats).

**Comment by dannyzaken** [comment]
specifically here we should probably handle the error in the code using io_stats_store. 
in general the we need to revisit the way we store stats in the DB and try to get rid of the `upsert` implementation and the advisory locks
