### ISSUE TITLE
A 4GB object can not put due to "InvalidBucketState"

### ISSUE THREAD

**Issue by mosamu** [noobaa/noobaa-core#7304]
### Environment info
- NooBaa Version: **noobaa-core-master**
- Platform: **Standalone**

### Actual behavior
A 4GB object can not put due to "InvalidBucketState".
```
[mosamu@ltfs209 noobaa-core-master]$ node src/tools/s3cat --endpoint http://localhost:6001/ --sig s3 --bucket bucket209 --put object209 --size 4096                                
Uploading object209 from generated data of size 4.0 GB                                                                                                                            
Upload Speed: 543.9 MB/sec (average 543.9)                                                                                                                                        
Upload Speed: 512.0 MB/sec (average 528.4)                                                                                                                                        
Upload Speed: 471.5 MB/sec (average 509.6)                                                                                                                                        
Upload Speed: 384.0 MB/sec (average 478.8)                                                                                                                                        
Upload Speed: 410.3 MB/sec (average 465.1)                                                                                                                                        
Upload Speed: 537.5 MB/sec (average 477.1)                                                                                                                                        
Upload Speed: 571.4 MB/sec (average 490.5)                                                                                                                                        
Upload Speed: 576.0 MB/sec (average 501.0)                                                                                                                                        
Upload Speed: 32.0 MB/sec (average 449.6)                                                                                                                                         
Upload Speed: 0.0 MB/sec (average 405.1)                                                                                                                                          
Upload Speed: 0.0 MB/sec (average 368.5)                                                                                                                                          
Upload Speed: 0.0 MB/sec (average 338.1)                                                                                                                                          
Upload Speed: 0.0 MB/sec (average 312.3)                                                                                                                                          
Upload Speed: 0.0 MB/sec (average 290.2)                                                                                                                                          
Upload Speed: 0.0 MB/sec (average 270.9)                                                                                                                                          
Upload Speed: 0.0 MB/sec (average 254.1)                                                                                                                                          
Upload Speed: 0.0 MB/sec (average 239.3)                                                                                                                                          
Upload Speed: 0.0 MB/sec (average 226.1)                                                                                                                                          
UPLOAD ERROR: InvalidBucketState: The request is not valid with the current state of the bucket.                                                                                  
    at Request.extractError (/home/mosamu/noobaa-core-master/node_modules/aws-sdk/lib/services/s3.js:711:35)                                                                      
    at Request.callListeners (/home/mosamu/noobaa-core-master/node_modules/aws-sdk/lib/sequential_executor.js:106:20)                                                             
    at Request.emit (/home/mosamu/noobaa-core-master/node_modules/aws-sdk/lib/sequential_executor.js:78:10)                                                                       
    at Request.emit (/home/mosamu/noobaa-core-master/node_modules/aws-sdk/lib/request.js:686:14)                                                                                  
    at Request.transition (/home/mosamu/noobaa-core-master/node_modules/aws-sdk/lib/request.js:22:10)                                                                             
    at AcceptorStateMachine.runTo (/home/mosamu/noobaa-core-master/node_modules/aws-sdk/lib/state_machine.js:14:12)                                                               
    at /home/mosamu/noobaa-core-master/node_modules/aws-sdk/lib/state_machine.js:26:10                                                                                            
    at Request.<anonymous> (/home/mosamu/noobaa-core-master/node_modules/aws-sdk/lib/request.js:38:9)                                                                             
    at Request.<anonymous> (/home/mosamu/noobaa-core-master/node_modules/aws-sdk/lib/request.js:688:12)                                                                           
    at Request.callListeners (/home/mosamu/noobaa-core-master/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {                                                           
  code: 'InvalidBucketState',                                                                                                                                                     
  region: null,                                                                                                                                                                   
  time: 2023-05-22T03:56:25.598Z,                                                                                                                                                 
  requestId: 'lhybewou-2gi1so-u2w',                                                                                                                                               
  extendedRequestId: 'lhybewou-2gi1so-u2w',                                                                                                                                       
  cfId: undefined,                                                                                                                                                                
  statusCode: 409,                                                                                                                                                                
  retryable: false,                                                                                                                                                               
  retryDelay: 74.71361244862989                                                                                                                                                   
}
```
I checked the backing store `/tmfs` had enough space.
```
[root@ltfs209 etc]# df -h /tmfs
Filesystem      Size  Used Avail Use% Mounted on
tmfs             48G  2.4G   46G   5% /tmfs
```
***
A smaller object like `512M` seemdsto be OK
```
[mosamu@ltfs209 noobaa-core-master]$ node src/tools/s3cat --endpoint http://localhost:6001/ --sig s3 --bucket bucket209 --put object209-512 --size 512
Uploading object209-512 from generated data of size 512 MB
Upload Speed: 489.0 MB/sec (average 489.0)
Upload Speed: 0.0 MB/sec (average 250.1)
Upload Speed: 0.0 MB/sec (average 168.0)
Upload Speed: 0.0 MB/sec (average 126.4)
Upload Speed: 0.0 MB/sec (average 101.4)
upload done. 101 MB/sec
```

### Expected behavior
The object must be `put`.

### Steps to reproduce
Using a big object(e.g. 4GB) can produce the error.

### More information - Screenshots / Logs / Other output
Refer to the output described at `Actual behavior`

**Comment by piste-jp-ibm** [comment]
@guymguym ,

As we discussed yesterday. It is good to ignore the error of `setxattr()` against `user._trigger.migrate`. This behavior might not spoil the automatic recovery logic in the backing store.

This is not a high priority issue anymore.
