### ISSUE TITLE
NSFS update content-type from cyberduck fails

### ISSUE THREAD

**Issue by motorman-ibm** [noobaa/noobaa-core#7421]
Openshift 4.10.46
ODF MCG 

cyberduck
```
running with ns-fs
choosing object /obcprestotpcds/sf1000/tpcds1kpqt/reason

get info /  metadata
content-type application/octet-stream	

Change content-type to application/x-directory
```

output from endpoint
```
. . .
Aug-1 19:48:40.613 [Endpoint/14]    [L0] core.sdk.namespace_fs:: check_bucket_boundaries: fs_account_config { gid: 0, uid: 0, nsfs_only: true, new_buckets_path: '/', backend: 'GPFS', warn_threshold_ms: 100 } file_path /nsfs/pvc-pv-prestotpcds/sf1000/tpcds1kpqt/reason/.folder
Aug-1 19:48:40.615 [Endpoint/14]    [L0] core.sdk.namespace_fs:: check_bucket_boundaries: fs_account_config { gid: 0, uid: 0, nsfs_only: true, new_buckets_path: '/', backend: 'GPFS', warn_threshold_ms: 100 } file_path /nsfs/pvc-pv-prestotpcds/sf1000/tpcds1kpqt/reason/.folder
Aug-1 19:48:40.615 [Endpoint/14]    [L0] core.sdk.namespace_fs:: check_bucket_boundaries: fs_account_config { gid: 0, uid: 0, nsfs_only: true, new_buckets_path: '/', backend: 'GPFS', warn_threshold_ms: 100 } file_path /nsfs/pvc-pv-prestotpcds/sf1000/tpcds1kpqt/reason/.folder
Aug-1 19:48:40.616 [Endpoint/14]    [L0] core.sdk.namespace_fs:: NamespaceFS: read_object_stream { file_path: '/nsfs/pvc-pv-prestotpcds/sf1000/tpcds1kpqt/reason/.folder', start: 0, end: Infinity }
Aug-1 19:48:40.620 [Endpoint/14]    [L0] core.sdk.namespace_fs:: NamespaceFS: read_object_stream completed file /nsfs/pvc-pv-prestotpcds/sf1000/tpcds1kpqt/reason/.folder { num_bytes: 0, num_buffers: 0, avg_buffer: NaN, log2_size_histogram: {} }
Aug-1 19:48:40.818 [Endpoint/14] [ERROR] core.endpoint.s3.s3_rest:: S3 ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>AccessDenied</Code><Message>Access Denied</Message><Resource>/obcprestotpcds/sf1000/tpcds1kpqt/reason/?acl=</Resource><RequestId>lksppe36-8cg5me-194r</RequestId></Error> PUT /obcprestotpcds/sf1000/tpcds1kpqt/reason/?acl= {"date":"Tue, 01 Aug 2023 19:47:45 GMT","expect":"100-continue","content-type":"text/plain","x-amz-content-sha256":"c31f9a29fc0e229dd1fdefe653f76096b89f9bdfbb41697f3b2f0d599fcb045d","x-amz-date":"20230801T194745Z","authorization":"AWS4-HMAC-SHA256 Credential=iJYC8inFPJN380vefArw/20230801/us-east-1/s3/aws4_request,SignedHeaders=content-type;date;host;x-amz-content-sha256;x-amz-date,Signature=dc661bc6ec74069a4255e6c9d39838780f391ae42e09001910f3441390e63b77","content-length":"351","user-agent":"Cyberduck/8.6.0.39818 (Windows 10/10.0.22621.0) (amd64)","accept-encoding":"gzip,deflate","host":"s3-openshift-storage.apps.ocp-cluster1.fusion-arc.res.ibm.com","x-forwarded-host":"s3-openshift-storage.apps.ocp-cluster1.fusion-arc.res.ibm.com","x-forwarded-port":"80","x-forwarded-proto":"http","forwarded":"for=9.61.21.3;host=s3-openshift-storage.apps.ocp-cluster1.fusion-arc.res.ibm.com;proto=http","x-forwarded-for":"9.61.21.3"} Error: Access Denied
    at Object.put_object_acl [as handler] (/root/node_modules/noobaa-core/src/endpoint/s3/ops/s3_put_object_acl.js:11:15)
    at handle_request (/root/node_modules/noobaa-core/src/endpoint/s3/s3_rest.js:149:28)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.s3_rest [as handler] (/root/node_modules/noobaa-core/src/endpoint/s3/s3_rest.js:68:9)

```

**Comment by guymguym** [comment]
@nimrod-becker @romayalon 

This is an attempt to set the content-type on a directory object which presto checks - 
https://github.com/prestodb/presto/blob/0515f186a8d3bf3412dfef4335a707ad2f9b0f57/presto-hive/src/main/java/com/facebook/presto/hive/s3/PrestoS3FileSystem.java#L377

Some more context - 
1. Recently I added the option to store/retrieve content-type on nsfs using xattr (see #7390).
2. Since this fix was not available on that version (ODF 4.10) Greg tried to use Cyberduck to update the content-type, which actually calls copy-object onto the same name. This can be confusing from nsfs side, because the intention is not to replace the library itself on the FS, just to update attributes.

In any case there's this failure above of put_object_acl which we need to bypass, and check that the operation works and sets the content-type.

Can this be assigned ?

**Comment by romayalon** [comment]
@motorman-ibm @guymguym 
I started working on it and these are my observations - 
create directory - works successfully, cyber duck claims that the size is 0 as expected. (content type is application/octet-stream)
copy directory - acl issue passed (thanks to https://github.com/noobaa/noobaa-core/pull/7391) but the request won't respond because cyber duck claims that the size is 64 (not as expected), we are waiting for data and none arrives...

**Comment by guymguym** [comment]
doesn't it send a copy-object?
