### ISSUE TITLE
NSFS | Files stored via SMB cannot be GET through S3

### ISSUE THREAD

**Issue by nhaustein** [noobaa/noobaa-core#7896]
### Environment info
- NooBaa Version: noobaa-core-5.16.0-20240304.el8.x86_64
- Platform: other: Storage Scale 5.1.9, RHEL 8.6
- 
### Actual behavior
1. S3 GET on file stored via SMB fails with: fatal error: An error occurred (500) when calling the HeadObject operation (reached max retries: 4): Internal Server Error

### Expected behavior
1. S3 GET on file stored via SMB should not fail

### Steps to reproduce
1. Create S3 account with UID and GID
2. Create bucket
3. PUT object
4. Export bucket path via smb (mmsmb export add)
5. Mount SMB share and store file in the bucket
6. GET file stored via SMB 

### More information - Screenshots / Logs / Other output
**GET file stored via SMB fails** 
$ s3u1 cp s3://test1/IBM-SSD24_CES-S3-technical.pptx ./
fatal error: An error occurred (500) when calling the HeadObject operation (reached max retries: 4): Internal Server Error

Noobaa log:
	Feb 23 20:38:31 scaleB-2 node[1169425]: [nsfs/1169425] [ERROR] core.endpoint.s3.s3_rest:: S3 ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><Resource>/test1/IBM-SSD24_CES-S3-technical.pptx</Resource><RequestId>lsz21thf-dw6cm3-dxg</RequestId></Error> HEAD /test1/IBM-SSD24_CES-S3-technical.pptx {"host":"10.7.67.165:6443","accept-encoding":"identity","user-agent":"aws-cli/1.32.46 md/Botocore#1.34.46 ua/2.0 os/linux#5.14.0-284.30.1.el9_2.x86_64 md/arch#x86_64 lang/python#3.9.16 md/pyimpl#CPython cfg/retry-mode#legacy botocore/1.34.46","x-amz-date":"20240223T193831Z","x-amz-content-sha256":"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855","authorization":"AWS4-HMAC-SHA256 Credential=fCZCVhcdL9YKrexcUSFU/20240223/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=a044e5fda191d8675263923ad477cdcf1cd994db29863282f5f732c5f8bab52d","amz-sdk-invocation-id":"0dd52a4f-a8ff-40a7-9f39-29aecb00e7f2","amz-sdk-request":"attempt=1"} TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received undefined    at new NodeError (node:internal/errors:406:5)    at Function.byteLength (node:buffer:775:11)    at set_response_xattr (/usr/local/noobaa-core/src/endpoint/s3/s3_utils.js:96:20)    at Object.set_response_object_md (/usr/local/noobaa-core/src/endpoint/s3/s3_utils.js:266:5)    at Object.head_object [as handler] (/usr/local/noobaa-core/src/endpoint/s3/ops/s3_head_object.js:29:14)    at async handle_request (/usr/local/noobaa-core/src/endpoint/s3/s3_rest.js:150:19)    at async Object.s3_rest [as handler] (/usr/local/noobaa-core/src/endpoint/s3/s3_rest.js:65:9)
	Feb 23 20:38:31 scaleB-2 node[1169425]: Feb-23 20:38:31.686 [nsfs/1169425] [ERROR] core.endpoint.s3.s3_rest:: S3 ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><Resource>/test1/IBM-SSD24_CES-S3-technical.pptx</Resource><RequestId>lsz21thf-dw6cm3-dxg</RequestId></Error> HEAD /test1/IBM-SSD24_CES-S3-technical.pptx {"host":"10.7.67.165:6443","accept-encoding":"identity","user-agent":"aws-cli/1.32.46 md/Botocore#1.34.46 ua/2.0 os/linux#5.14.0-284.30.1.el9_2.x86_64 md/arch#x86_64 lang/python#3.9.16 md/pyimpl#CPython cfg/retry-mode#legacy botocore/1.34.46","x-amz-date":"20240223T193831Z","x-amz-content-sha256":"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855","authorization":"AWS4-HMAC-SHA256 Credential=fCZCVhcdL9YKrexcUSFU/20240223/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=a044e5fda191d8675263923ad477cdcf1cd994db29863282f5f732c5f8bab52d","amz-sdk-invocation-id":"0dd52a4f-a8ff-40a7-9f39-29aecb00e7f2","amz-sdk-request":"attempt=1"} TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received undefined
	Feb 23 20:38:31 scaleB-2 node[1169425]:     at new NodeError (node:internal/errors:406:5)
	Feb 23 20:38:31 scaleB-2 node[1169425]:     at Function.byteLength (node:buffer:775:11)
	Feb 23 20:38:31 scaleB-2 node[1169425]:     at set_response_xattr (/usr/local/noobaa-core/src/endpoint/s3/s3_utils.js:96:20)
	Feb 23 20:38:31 scaleB-2 node[1169425]:     at Object.set_response_object_md (/usr/local/noobaa-core/src/endpoint/s3/s3_utils.js:266:5)
	Feb 23 20:38:31 scaleB-2 node[1169425]:     at Object.head_object [as handler] (/usr/local/noobaa-core/src/endpoint/s3/ops/s3_head_object.js:29:14)
	Feb 23 20:38:31 scaleB-2 node[1169425]:     at async handle_request (/usr/local/noobaa-core/src/endpoint/s3/s3_rest.js:150:19)
	Feb 23 20:38:31 scaleB-2 node[1169425]:     at async Object.s3_rest [as handler] (/usr/local/noobaa-core/src/endpoint/s3/s3_rest.js:65:9)

**Head object fails:**
$ s3u1api head-object --bucket test1 --key IBM-SSD24_CES-S3-technical.pptx
An error occurred (500) when calling the HeadObject operation (reached max retries: 4): Internal Server Error

**File has a strange attribute in GPFS:**
file name:            /gpfs/fs1/buckets/test1/IBM-SSD24_CES-S3-technical.pptx
metadata replication: 2 max 2
data replication:     2 max 2
immutable:            no
appendOnly:           no
flags:
storage pool name:    system
fileset name:         buckets
snapshot name:
creation time:        Fri Feb 23 20:10:03 2024
Misc attributes:      ARCHIVE
Encrypted:            no
user.$KERNEL.PURGE.SEC.FILEHASH: "????_46?U??-`???d?H?0?"?????????&,???????????3??????h??{|??????Gb?h?4??f]???f??Wy?]_}??????y???????????????w??~?zgz?j??g?_??[iv??zfm?????????''qL??8"

**Notes:**

- After deleting the attribute user.$KERNEL.PURGE.SEC.FILEHASH, the GET operation works!
- It seems this attribute is always attached to files that are stored via SMB
-

**Comment by janfrode** [comment]
To me this looks like noobaa doesn't like user xattrs with more than one dot. I.e. this is all I need to set on a file to trigger the issue:

`mmchattr --set-attr user.one.two filename.txt
`

**Comment by nhaustein** [comment]
Interesting @janfrode. We cannot prevent customers from setting xattrs. Noobaa should not get hung on these attrs. Perhaps it is an idea that Noobaa creates its own sub-namespace for user defined attributes under: user.noobaa. Problem is that the storage class attr does not match this, it is currently user.storage_class (no noobaa).

**Comment by guymguym** [comment]
@nimrod-becker @romayalon Is there a plan to fix this anytime soon?

**Comment by romayalon** [comment]
@guymguym @nimrod-becker i'll take it next week

**Comment by nhaustein** [comment]
Hi @romayalon , please note, that the attribute user.$KERNEL.PURGE.SEC.FILEHASH is obviously set by smb when SELinux is permissive or enforcing. This attr is not set, when SELinux is disabled.

**Comment by romayalon** [comment]
Thanks @nhaustein and @janfrode 
We actually had a bug in our code - I suggested a fix on https://github.com/noobaa/noobaa-core/pull/7986

**Comment by romayalon** [comment]
@nhaustein @janfrode I merged this fix to master, can you please verify?

**Comment by nhaustein** [comment]
@romayalon I tested with nightly build noobaa-core-5.17.0-20240422.el8.x86_64.rpm and it worked. I was able to download this file with the strange attributes. Thanks for your work.

Note, I have never seen this strange attribute:
user..PURGE.SEC.FILEHASH: "????_46?U??-`???d?H?0?"?????????&,???????????3??????h??{|??????Gb?h?4??f]???f??Wy?]_}??????y???????????????w??~?zgz?j??g?_??[iv??zfm?????????qL??8"
again in any of the systems I deployed noobaa. With the new build above it worked while with the build noobaa-core-5.16.0-20240304.el8.x86_64.rpm it did not work (I tested first with the old build and then with the new build).

Thanks for your great work

**Comment by guymguym** [comment]
Thanks for the verification @nhaustein. Closing.
