### ISSUE TITLE
NSFS | NC | get-bucket-policy-status fails with internal error (TypeError: policy.statement is not iterable)

### ISSUE THREAD

**Issue by guymguym** [noobaa/noobaa-core#7924]
### Environment info
- NooBaa Version: **5.15.0**
- Platform: **RHEL8**

### Actual behavior
1. get-bucket-policy works, but get-bucket-policy-status fails with internal error:

```sh
$ aws s3api --endpoint http://localhost:80 get-bucket-policy --bucket bucket1                                                                              
{
    "Policy": "{\"Statement\":[{\"Sid\":\"AllowEveryoneReadOnlyAccess\",\"Effect\":\"Allow\",\"Principal\":\"*\",\"Action\":[\"s3:GetObject\",\"s3:ListBucket\"],\"Resource\":[\"arn:aws:s3:::bucket1\",\"arn:aws:s3:::bucket1/*\"]}]}"
}

$ aws s3api --endpoint http://localhost:80 get-bucket-policy-status --bucket bucket1                                                                       

An error occurred (InternalError) when calling the GetBucketPolicyStatus operation (reached max retries: 4): We encountered an internal error. Please try again.  
```

From the log:
```js
2024-03-07T15:50:13.684579+09:00 server node[1833210]: [nsfs/1833210]    [L0] core.sdk.bucketspace_fs:: BucketSpaceFS.read_bucket_sdk_info: bucket_config_path /gpfs/nsfs/buckets/bucket1.json
2024-03-07T15:50:13.685137+09:00 server node[1833210]: [nsfs/1833210]    [L0] core.sdk.bucketspace_fs:: BucketSpaceFS.read_bucket_sdk_info: bucket_config_path /gpfs/nsfs/buckets/bucket1.json
2024-03-07T15:50:13.687272+09:00 server node[1833210]: [nsfs/1833210]    [L1] core.sdk.object_sdk:: validate_non_nsfs_bucket:  
  { 
    name: SENSITIVE-5cfd9f24ccdd38e2, 
    email: SENSITIVE-5cfd9f24ccdd38e2, 
    creation_date: '2024-03-06T03:38:40.902Z', 
    access_keys: [ { access_key: SENSITIVE-2ca9fc5184acac2a, secret_key: SENSITIVE-1c41343d78549359 } ], 
    nsfs_account_config: { uid: 0, gid: 10, new_buckets_path: '/gpfs/bucket-root', fs_backend: 'GPFS' }, 
    allow_bucket_creation: true, 
    _id: '65e7e540e397b951176d4055' 
  } { fs_root_path: '', fs_backend: 'GPFS' }
2024-03-07T15:50:13.687881+09:00 server node[1833210]: [nsfs/1833210]    [L1] core.endpoint.s3.s3_rest:: S3 REQUEST GET /bucket1?policyStatus op get_bucket_policy_status request_id ltgvbupc-dgo0b9-iz1 
  { 
    host: 'localhost', 
    'accept-encoding': 'identity', 
    'user-agent': 'aws-cli/1.23.2 Python/3.6.8 Linux/4.18.0-477.27.1.el8_8.x86_64 botocore/1.23.46', 
    'x-amz-date': '20240307T065013Z', 
    'x-amz-content-sha256': '...', 
    authorization: 'AWS4-HMAC-SHA256 ...' 
  }
2024-03-07T15:50:13.688515+09:00 server node[1833210]: [nsfs/1833210]    [L0] core.sdk.bucketspace_fs:: BucketSpaceFS.get_bucket_policy: Bucket name bucket1
2024-03-07T15:50:13.689263+09:00 server node[1833210]: [nsfs/1833210]    [L0] core.sdk.bucketspace_fs:: BucketSpaceFS.get_bucket_policy: policy 
  {  
    Statement: [ { 
      Sid: 'AllowEveryoneReadOnlyAccess', 
      Effect: 'Allow', 
      Principal: '*', 
      Action: [ 's3:GetObject', 's3:ListBucket' ], 
      Resource: [ 'arn:aws:s3:::bucket1', 'arn:aws:s3:::bucket1/*' ] 
    } ]
  }
2024-03-07T15:50:13.689969+09:00 server node[1833210]: [nsfs/1833210] [ERROR] core.endpoint.s3.s3_rest:: S3 ERROR 
  <?xml version="1.0" encoding="UTF-8"?>
  <Error>
    <Code>InternalError</Code>
    <Message>We encountered an internal error. Please try again.</Message>
    <Resource>/bucket1?policyStatus</Resource>
    <RequestId>ltgvbupc-dgo0b9-iz1</RequestId>
  </Error> 
  GET /bucket1?policyStatus {
    "host":"localhost",
    "accept-encoding":"identity",
    "user-agent":"aws-cli/1.23.2 Python/3.6.8 Linux/4.18.0-477.27.1.el8_8.x86_64 botocore/1.23.46",
    "x-amz-date":"20240307T065013Z",
    "x-amz-content-sha256":"...",
    "authorization":"...
  } 
  TypeError: policy.statement is not iterable
    at _is_policy_public (/usr/local/noobaa-core/src/endpoint/s3/ops/s3_get_bucket_policy_status.js:19:36)
    at Object.get_bucket_policy_status [as handler] (/usr/local/noobaa-core/src/endpoint/s3/ops/s3_get_bucket_policy_status.js:12:23)
    at async handle_request (/usr/local/noobaa-core/src/endpoint/s3/s3_rest.js:150:19)
    at async Object.s3_rest [as handler] (/usr/local/noobaa-core/src/endpoint/s3/s3_rest.js:65:9)

```

### Expected behavior
1. The output should be like below.

{
    "PolicyStatus": {
        "IsPublic": false
    }
}

### Steps to reproduce
1. See above

**Comment by liranmauda** [comment]
@nadavMiz 
Shouldn't all the fields of policy start with an upper case? 
https://docs.aws.amazon.com/cli/latest/reference/s3api/put-bucket-policy.html

**Comment by nadavMiz** [comment]
@liranmauda this is correct, I didn't change s3_get_bucket_policy_status after changing the schema. I'll fix this

**Comment by liranmauda** [comment]
Fixed by https://github.com/noobaa/noobaa-core/pull/7926

**Comment by romayalon** [comment]
reopening due to failed on validation
