### ISSUE TITLE
NSFS | S3 | Versioning: After creating 5 object versions in parallel threads ListObjectVersions only lists two versions

### ISSUE THREAD

**Issue by hseipp** [noobaa/noobaa-core#8316]
### Environment info
- NooBaa Version: **5.15.4**
- Platform: **CentOS 8, deployed using [https://github.com/IBM/StorageScaleVagrant](https://github.com/IBM/StorageScaleVagrant)**

### Actual behavior

Five multiple threads perform PutObject to the same key in a versioned bucket. After the operations completed, ListObjectVersions only delivers two objects.

### Expected behavior

PutObject in simultaneously running threads to the same key should lead to as many versions as threads got spawned.

### Steps to reproduce

Run Ceph s3-tests, method `test_versioned_concurrent_object_create_concurrent_remove()`:

```
S3TEST_CONF=s3tests.conf tox -- s3tests_boto3/functional/test_s3.py::test_versioned_concurrent_object_create_concurrent_remove
...
        for i in range(5):
            t = _do_create_versioned_obj_concurrent(client, bucket_name, key, num_versions)
            _do_wait_completion(t)
    
            response = client.list_object_versions(Bucket=bucket_name)
            versions = response['Versions']
    
>           assert len(versions) == num_versions
E           assert 2 == 5
E            +  where 2 = len([{'ETag': '"mtime-d3roiq22g5c0-ino-1c03"', 'IsLatest': True, 'Key': 'myobj', 'LastModified': datetime.datetime(2024, 8..., 'IsLatest': True, 'Key': 'myobj', 'LastModified': datetime.datetime(2024, 8, 28, 16, 18, 38, tzinfo=tzlocal()), ...}])
```

Please note that s3-tests outputs the following in the "warnings summary" for the operation:
```
s3tests_boto3/functional/test_s3.py::test_versioned_concurrent_object_create_concurrent_remove
  /home/vagrant/s3-tests/.tox/py/lib/python3.8/site-packages/_pytest/threadexception.py:82: PytestUnhandledThreadExceptionWarning: Exception in thread Thread-2
  
  Traceback (most recent call last):
    File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
      self.run()
    File "/usr/lib64/python3.8/threading.py", line 870, in run
      self._target(*self._args, **self._kwargs)
    File "/home/vagrant/s3-tests/s3tests_boto3/functional/test_s3.py", line 8034, in _do_create_object
      client.put_object(Bucket=bucket_name, Key=key, Body=body)
    File "/home/vagrant/s3-tests/.tox/py/lib/python3.8/site-packages/botocore/client.py", line 569, in _api_call
      return self._make_api_call(operation_name, kwargs)
    File "/home/vagrant/s3-tests/.tox/py/lib/python3.8/site-packages/botocore/client.py", line 1023, in _make_api_call
      raise error_class(parsed_response, operation_name)
  botocore.errorfactory.BucketAlreadyExists: An error occurred (BucketAlreadyExists) when calling the PutObject operation: The requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again.
  
    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))
```

which seems to be a wrong error message as we are only using one bucket name for all the operations and the bucket was created before PutObject got executed.

### More information - Screenshots / Logs / Other output

Noobaa log file with "all" log level:

[noobaa_20240828_1836.log.gz](https://github.com/user-attachments/files/16786461/noobaa_20240828_1836.log.gz)

**Comment by romayalon** [comment]
@nadavMiz can you please take a look?

**Comment by hseipp** [comment]
Re-tested today with noobaa-core 5.17.0 20241007, Scale 5.2.2.0 20241004 and the issue is still there.

Repeating the test, it sometimes fails with `assert 4 == 5`, `assert 3 == 5` or even passed that test code that verified that ListObjectVersions has written all the objects, but then fails at teardown with a `BucketNotEmpty` error.
This is due to ListObjectVersions that is used to determine what needs to be cleaned up at teardown is not reporting the last written object version and/or Delete Marker.

Please note that the same issues during runtime and teardown also occur with `test_s3cever22` where only PutObject operations are used.

**Comment by hseipp** [comment]
Additionally, `test_versioned_concurrent_object_create_and_remove()` occasionally fails with an AssertionError after deleting all versions, meaning that there were leftover versions reported with ListObjectVersions even after all versions got deleted using parallel threads.

**Comment by hseipp** [comment]
Another incarnation occurring in `test_versioning_obj_suspended_copy()`. It fails with a `BucketNotEmpty` error during the `clean_up_bucket()` phase. So again, the DeleteObject operations for all VersionIds return with success, but are not done when the DeleteBucket operation is being carried out.

Noobaa logs at "all" debug level attached
[noobaa-20241008_3.log.gz](https://github.com/user-attachments/files/17296279/noobaa-20241008_3.log.gz)

**Comment by hseipp** [comment]
With noobaa-core 5.17.0 20241012, Scale 5.2.2.0 20241004, the issue can still be reproduced. It fails with `4 == 5`, re-retesting it occasionally also fails with `assert 3 == 5`. A "all" level log is attached.
[noobaa-20241014_1.log.gz](https://github.com/user-attachments/files/17362239/noobaa-20241014_1.log.gz)

Also `test_versioning_obj_suspended_copy()` fails when trying to delete an object, might or might not be the same issue. The DeleteObject fails with `botocore.exceptions.ClientError: An error occurred (InternalError) when calling the DeleteObject operation (reached max retries: 4): We encountered an internal error…`.  Log with "all" level is attached
[noobaa-20241014_2.log.gz](https://github.com/user-attachments/files/17362373/noobaa-20241014_2.log.gz)

**Comment by romayalon** [comment]
@hseipp @nadavMiz merged this fix https://github.com/noobaa/noobaa-core/pull/8455
it's not reproducible anymore, is that correct?

**Comment by hseipp** [comment]
> @hseipp @nadavMiz merged this fix #8455 2 weeks ago it's not reproducible anymore, is that correct?
Correct, the `test_versioned_concurrent_object_create_concurrent_remove()` issue is not reproducible anymore since the 20241015 noobaa-core release.
For the `test_versioning_obj_suspended_copy()` issue that looked similar and is still occurring with builds up to 20241023, I opened #8469.
