### ISSUE TITLE
Warp with versioned, enablemd5 true, ran into "We encountered an internal error. Please try again" PUT method errors 

### ISSUE THREAD

**Issue by rkomandu** [noobaa/noobaa-core#8524]
### Environment info
- NooBaa Version: **VERSION**
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify**

noobaa-core-5.17.1-20241104.el9.ppc64le (standalone) 

### Actual behavior
1.

```
Warp was run for versioned enabled bucket, observed the 

./warp versioned --insecure --duration 180m --host gpfs-p10-s3-ces.rtp.raleigh.ibm.com:6443 --access-key KCxP4AN9937kVqoCrNIs --secret-key bIdwF/5nJtSnrHWXrhPOhkv1WqGjtayMk6D+aU/U --tls --obj.size 256M --bucket newbucket-warp-vers-mup-13nov

warp: <ERROR> upload error:  We encountered an internal error. Please try again.
warp: <ERROR> short upload. want:256000000, got:0
warp: <ERROR> upload error:  We encountered an internal error. Please try again.
warp: <ERROR> short upload. want:256000000, got:0
warp: <ERROR> upload error:  We encountered an internal error. Please try again.
warp: <ERROR> short upload. want:256000000, got:0
warp: <ERROR> upload error:  We encountered an internal error. Please try again.
warp: <ERROR> short upload. want:256000000, got:0
warp: Benchmark data written to "warp-versioned-2024-11-13[002802]-3u4C.csv.zst"
Mixed operations.
Operation: DELETE, 10%, Concurrency: 20, Ran 2h59m58s.
 * Throughput: 0.46 obj/s

Operation: GET, 45%, Concurrency: 20, Ran 3h0m4s.
 * Throughput: 500.46 MiB/s, 2.05 obj/s

Operation: PUT, 15%, Concurrency: 20, Ran 3h0m4s.
Errors: 4
 * Throughput: 166.92 MiB/s, 0.68 obj/s

Operation: STAT, 30%, Concurrency: 20, Ran 2h59m58s.
 * Throughput: 1.37 obj/s

Cluster Total: 667.40 MiB/s, 4.56 obj/s, 4 errors over 3h0m0s.
Total Errors:4.
warp: Cleanup Done

```
ERROR in the noobaa.log (snippet is copied) --> more in the logs 

Nov 13 02:20:39 node-gui1 [3689895]: [nsfs/3689895] [ERROR] core.endpoint.s3.s3_rest:: S3 ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>Interna
lError</Code><Message>We encountered an internal error. Please try again.</Message><Resource>/newbucket-warp-vers-mup-13nov/n9pjzZ6F/5.7eWO9uYt8k5sK7Wn.rnd?up
loadId=bd897211-764d-48a6-a572-73bf184e750e</Resource><RequestId>m3fjvnp1-1bh1z0-1nv</RequestId></Error> POST /newbucket-warp-vers-mup-13nov/n9pjzZ6F/5.7eWO9u
Yt8k5sK7Wn.rnd?uploadId=bd897211-764d-48a6-a572-73bf184e750e {"host":"gpfs-p10-s3-ces.rtp.raleigh.ibm.com:6443","user-agent":"MinIO (linux; ppc64le) minio-go/
v7.0.70 warp/(dev)","content-length":"1450","authorization":"AWS4-HMAC-SHA256 Credential=KCxP4AN9937kVqoCrNIs/20241113/us-east-1/s3/aws4_request, SignedHeader
s=content-type;host;x-amz-checksum-crc32c;x-amz-content-sha256;x-amz-date, Signature=259d9b307e73f794210a9ea45b43da9818ba49cbca69c3ac409e0e1f76f499ce","conten
t-type":"application/octet-stream","x-amz-checksum-crc32c":"DiTesA==","x-amz-content-sha256":"dbc6f5a50de4dfc013242d1332e6e6caf77d458a4040248a85a5d6b8ef56085a
","x-amz-date":"20241113T071859Z"} Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client    at ServerResponse.setHeader (node:_h
ttp_outgoing:652:11)    at Object.post_object_uploadId [as handler] (/usr/local/noobaa-core/src/endpoint/s3/ops/s3_post_object_uploadId.js:43:13)    at async handle_request (/usr/local/noobaa-core/src/endpoint/s3/s3_rest.js:161:19)    at async Object.s3_rest [as handler] (/usr/local/noobaa-core/src/endpoint/s3/s3_rest.js:66:9)
Nov 13 02:20:39 node-gui1 [3689895]: [nsfs/3689895]    [L0] core.endpoint.s3.s3_rest:: Sending error xml in body, but too late for headers...
...

s3 configuration 
------------------------
 ALLOW_HTTP : false
 DEBUGLEVEL : default
 ENABLEMD5 : true
 ENDPOINT_FORKS : 2
 ENDPOINT_PORT : 6001
 ENDPOINT_SSL_PORT : 6443

### Expected behavior
1.

4 errors are observed 

Operation: PUT (7391). Ran 3h0m4s. Size: 256000000 bytes. Concurrency: 20.
Errors: 4
First Errors:
 * https://<cesip>:6443, 2024-11-13 02:20:40 -0500 EST: We encountered an internal error. Please try again.
 * https://<cesip>:6443, 2024-11-13 02:20:40 -0500 EST: We encountered an internal error. Please try again.
 * https://<cesip>:6443, 2024-11-13 02:23:01 -0500 EST: We encountered an internal error. Please try again.
 * https://<cesip>:6443, 2024-11-13 02:30:02 -0500 EST: We encountered an internal error. Please try again.

### Steps to reproduce
1.
Run Warp as shown above with options , enablemd5=true 

### More information - Screenshots / Logs / Other output
will upload the logs to box folder and update here

**Comment by nadavMiz** [comment]
@rkomandu the box is empty.  any news about the logs?

**Comment by rkomandu** [comment]
reposting again the box folder --> https://ibm.ent.box.com/folder/293689458577

**Comment by nadavMiz** [comment]
@rkomandu looks like the connection is closed during put:
```
Nov 13 00:25:26 gpfs-p10-gui0 [3532905]: [nsfs/3532905] [ERROR] core.sdk.namespace_fs:: namespace_fs._upload_stream: error occured on stream ChunkFS:  Error: aborted    at connResetException (node:interna
l/errors:787:14)    at abortIncoming (node:_http_server:793:17)    at socketOnClose (node:_http_server:787:3)    at TLSSocket.emit (node:events:530:35)    at TLSSocket.emit (node:domain:488:12)    at node
:net:337:12    at Socket.done (node:_tls_wrap:657:7)    at Object.onceWrapper (node:events:633:26)    at Socket.emit (node:events:530:35)    at Socket.emit (node:domain:488:12) {  code: 'ECONNRESET'}
Nov 13 00:25:26 gpfs-p10-gui0 [3532905]: [nsfs/3532905] [ERROR] core.sdk.namespace_fs:: _upload_stream had error:  Error: aborted    at connResetException (node:internal/errors:787:14)    at abortIncoming
 (node:_http_server:793:17)    at socketOnClose (node:_http_server:787:3)    at TLSSocket.emit (node:events:530:35)    at TLSSocket.emit (node:domain:488:12)    at node:net:337:12    at Socket.done (node:
_tls_wrap:657:7)    at Object.onceWrapper (node:events:633:26)    at Socket.emit (node:events:530:35)    at Socket.emit (node:domain:488:12) {  code: 'ECONNRESET'}
Nov 13 00:25:26 gpfs-p10-gui0 [3532905]: [nsfs/3532905] [ERROR] core.sdk.namespace_fs:: namespace_fs._upload_stream: error occured on stream ChunkFS:  Error: aborted    at connResetException (node:interna
l/errors:787:14)    at abortIncoming (node:_http_server:793:17)    at socketOnClose (node:_http_server:787:3)    at TLSSocket.emit (node:events:530:35)    at TLSSocket.emit (node:domain:488:12)    at node
:net:337:12    at Socket.done (node:_tls_wrap:657:7)    at Object.onceWrapper (node:events:633:26)    at Socket.emit (node:events:530:35)    at Socket.emit (node:domain:488:12) {  code: 'ECONNRESET'}
Nov 13 00:25:26 gpfs-p10-gui0 [3532905]: [nsfs/3532905] [ERROR] core.sdk.namespace_fs:: _upload_stream had error:  Error: aborted    at connResetException (node:internal/errors:787:14)    at abortIncoming
 (node:_http_server:793:17)    at socketOnClose (node:_http_server:787:3)    at TLSSocket.emit (node:events:530:35)    at TLSSocket.emit (node:domain:488:12)    at node:net:337:12    at Socket.done (node:
_tls_wrap:657:7)    at Object.onceWrapper (node:events:633:26)    at Socket.emit (node:events:530:35)    at Socket.emit (node:domain:488:12) {  code: 'ECONNRESET'}
Nov 13 00:25:26 gpfs-p10-gui0 [3532905]: [nsfs/3532905] [ERROR] core.endpoint.s3.s3_rest:: S3 ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>InternalError</Code><Message>We encountered an intern
al error. Please try again.</Message><Resource>/newbucket-warp-vers-mup/v5FwEkOw/1.HvjBdX7COBxGhP91.rnd?partNumber=6&amp;uploadId=af45d41f-aa94-4560-a90d-38577cd7ef37</Resource><RequestId>m3fftmk4-dx6nk8-
cia</RequestId></Error> PUT /newbucket-warp-vers-mup/v5FwEkOw/1.HvjBdX7COBxGhP91.rnd?partNumber=6&uploadId=af45d41f-aa94-4560-a90d-38577cd7ef37 {"host":"gpfs-p10-s3-ces.rtp.raleigh.ibm.com:6443","user-age
nt":"MinIO (linux; ppc64le) minio-go/v7.0.70 warp/(dev)","content-length":"16777216","authorization":"AWS4-HMAC-SHA256 Credential=KCxP4AN9937kVqoCrNIs/20241113/us-east-1/s3/aws4_request, SignedHeaders=hos
t;x-amz-checksum-crc32c;x-amz-content-sha256;x-amz-date, Signature=2253b17aff3ef7192bda3b45252346211d809bed116f8b4d708bf915a0811235","x-amz-checksum-crc32c":"9WP0PQ==","x-amz-content-sha256":"UNSIGNED-PAY
LOAD","x-amz-date":"20241113T052526Z"} Error: aborted    at connResetException (node:internal/errors:787:14)    at abortIncoming (node:_http_server:793:17)    at socketOnClose (node:_http_server:787:3)   
 at TLSSocket.emit (node:events:530:35)    at TLSSocket.emit (node:domain:488:12)    at node:net:337:12    at Socket.done (node:_tls_wrap:657:7)    at Object.onceWrapper (node:events:633:26)    at Socket.
emit (node:events:530:35)    at Socket.emit (node:domain:488:12)
``` 

we first need to understand who closes the connection. 
the issue doesn't recreate on my environment. 

can you run:
`tcpdump -w record.pcap '(tcp[tcpflags] & (tcp-fin|tcp-rst)) != 0'`
on the node during the test. this will record all closing of connection, and maybe will give us a clue to who initiated the close

also can you run the test with full logs:
`mms3 config change DEBUGLEVEL="all"`
this will give more information to what went on

**Comment by nadavMiz** [comment]
on the time these 4 errors happen we see the following error:
```
Nov 13 02:20:39 gpfs-p10-gui1 [3689895]: [nsfs/3689895] [ERROR] core.endpoint.s3.s3_rest:: S3 ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><Resource>/newbucket-warp-vers-mup-13nov/n9pjzZ6F/5.7eWO9uYt8k5sK7Wn.rnd?uploadId=bd897211-764d-48a6-a572-73bf184e750e</Resource><RequestId>m3fjvnp1-1bh1z0-1nv</RequestId></Error> POST /newbucket-warp-vers-mup-13nov/n9pjzZ6F/5.7eWO9uYt8k5sK7Wn.rnd?uploadId=bd897211-764d-48a6-a572-73bf184e750e {"host":"gpfs-p10-s3-ces.rtp.raleigh.ibm.com:6443","user-agent":"MinIO (linux; ppc64le) minio-go/v7.0.70 warp/(dev)","content-length":"1450","authorization":"AWS4-HMAC-SHA256 Credential=KCxP4AN9937kVqoCrNIs/20241113/us-east-1/s3/aws4_request, SignedHeaders=content-type;host;x-amz-checksum-crc32c;x-amz-content-sha256;x-amz-date, Signature=259d9b307e73f794210a9ea45b43da9818ba49cbca69c3ac409e0e1f76f499ce","content-type":"application/octet-stream","x-amz-checksum-crc32c":"DiTesA==","x-amz-content-sha256":"dbc6f5a50de4dfc013242d1332e6e6caf77d458a4040248a85a5d6b8ef56085a","x-amz-date":"20241113T071859Z"} Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client    at ServerResponse.setHeader (node:_http_outgoing:652:11)    at Object.post_object_uploadId [as handler] (/usr/local/noobaa-core/src/endpoint/s3/ops/s3_post_object_uploadId.js:43:13)    at async handle_request (/usr/local/noobaa-core/src/endpoint/s3/s3_rest.js:161:19)    at async Object.s3_rest [as handler] (/usr/local/noobaa-core/src/endpoint/s3/s3_rest.js:66:9)
```
might not be related but right before that we get warnings of FS commands taking too long:
```
Nov 13 02:20:39 gpfs-p10-gui1 [3689891]: 2024-11-13 02:20:39.580321 [PID-3689891/TID-3689928] [L0] FS::FSWorker::Execute: WARNING Unlink _path=/ibm/fvt_fs/s3user-17001-dir/newbucket-warp-vers-mup-13nov/.n
oobaa-nsfs_673437d3edd92ddbf1c85cdd/multipart-uploads/25cf8cc4-f1bb-4d01-8a4c-81dbb239a9ce/part-7  took too long: 132.432 ms
Nov 13 02:20:39 gpfs-p10-gui1 [3689895]: 2024-11-13 02:20:39.581724 [PID-3689895/TID-3689943] [L0] FS::FSWorker::Execute: WARNING Unlink _path=/ibm/fvt_fs/s3user-17001-dir/newbucket-warp-vers-mup-13nov/.n
oobaa-nsfs_673437d3edd92ddbf1c85cdd/multipart-uploads/bd897211-764d-48a6-a572-73bf184e750e/part-1  took too long: 132.659 ms
Nov 13 02:20:39 gpfs-p10-gui1 [3689895]: 2024-11-13 02:20:39.581829 [PID-3689895/TID-3689955] [L0] FS::FSWorker::Execute: WARNING Unlink _path=/ibm/fvt_fs/s3user-17001-dir/newbucket-warp-vers-mup-13nov/.n
oobaa-nsfs_673437d3edd92ddbf1c85cdd/multipart-uploads/bd897211-764d-48a6-a572-73bf184e750e/part-15  took too long: 109.97 ms
Nov 13 02:20:39 gpfs-p10-gui1 [3689891]: 2024-11-13 02:20:39.586127 [PID-3689891/TID-3689933] [L0] FS::FSWorker::Execute: WARNING Unlink _path=/ibm/fvt_fs/s3user-17001-dir/newbucket-warp-vers-mup-13nov/.n
oobaa-nsfs_673437d3edd92ddbf1c85cdd/multipart-uploads/25cf8cc4-f1bb-4d01-8a4c-81dbb239a9ce/part-2  took too long: 138.213 ms
Nov 13 02:20:39 gpfs-p10-gui1 [3689891]: 2024-11-13 02:20:39.591514 [PID-3689891/TID-3689937] [L0] FS::FSWorker::Execute: WARNING Unlink _path=/ibm/fvt_fs/s3user-17001-dir/newbucket-warp-vers-mup-13nov/.n
oobaa-nsfs_673437d3edd92ddbf1c85cdd/multipart-uploads/25cf8cc4-f1bb-4d01-8a4c-81dbb239a9ce/part-6  took too long: 143.57 ms
Nov 13 02:20:39 gpfs-p10-gui1 [3689891]: 2024-11-13 02:20:39.600428 [PID-3689891/TID-3689926] [L0] FS::FSWorker::Execute: WARNING Unlink _path=/ibm/fvt_fs/s3user-17001-dir/newbucket-warp-vers-mup-13nov/.n
oobaa-nsfs_673437d3edd92ddbf1c85cdd/multipart-uploads/25cf8cc4-f1bb-4d01-8a4c-81dbb239a9ce/part-1  took too long: 134.905 ms
Nov 13 02:20:39 gpfs-p10-gui1 [3689891]: 2024-11-13 02:20:39.600500 [PID-3689891/TID-3689931] [L0] FS::FSWorker::Execute: WARNING Unlink _path=/ibm/fvt_fs/s3user-17001-dir/newbucket-warp-vers-mup-13nov/.n
oobaa-nsfs_673437d3edd92ddbf1c85cdd/multipart-uploads/25cf8cc4-f1bb-4d01-8a4c-81dbb239a9ce/part-15  took too long: 101.728 ms
```

**Comment by nadavMiz** [comment]
@rkomandu can you take full logs, so I can farther investigate this:
`mms3 config change DEBUGLEVEL="all"`

**Comment by rkomandu** [comment]
@nadavMiz , you can check this, it had 8 errors from the Warp summary 

```
./warp-script.sh 2>&1 | tee ./warp-vers-issue8524-19Nov.log
warp: <ERROR> upload error:  We encountered an internal error. Please try again.
warp: <ERROR> short upload. want:256000000, got:0
warp: <ERROR> upload error:  We encountered an internal error. Please try again.
warp: <ERROR> short upload. want:256000000, got:0
warp: <ERROR> upload error:  We encountered an internal error. Please try again.
warp: <ERROR> short upload. want:256000000, got:0
warp: <ERROR> upload error:  We encountered an internal error. Please try again.
warp: <ERROR> short upload. want:256000000, got:0
warp: <ERROR> upload error:  We encountered an internal error. Please try again.
warp: <ERROR> short upload. want:256000000, got:0
warp: <ERROR> upload error:  We encountered an internal error. Please try again.
warp: <ERROR> short upload. want:256000000, got:0
warp: <ERROR> upload error:  We encountered an internal error. Please try again.
warp: <ERROR> short upload. want:256000000, got:0
warp: <ERROR> upload error:  We encountered an internal error. Please try again.
warp: <ERROR> short upload. want:256000000, got:0
warp: Benchmark data written to "warp-versioned-2024-11-19[000053]-MgrT.csv.zst"
Mixed operations.
Operation: DELETE, 10%, Concurrency: 20, Ran 2h59m56s.
 * Throughput: 0.44 obj/s

Operation: GET, 45%, Concurrency: 20, Ran 3h0m3s.
 * Throughput: 480.33 MiB/s, 1.97 obj/s

Operation: PUT, 15%, Concurrency: 20, Ran 3h0m1s.
Errors: 8
 * Throughput: 160.12 MiB/s, 0.66 obj/s

Operation: STAT, 30%, Concurrency: 20, Ran 2h59m59s.
 * Throughput: 1.31 obj/s

Cluster Total: 640.49 MiB/s, 4.37 obj/s, 8 errors over 2h59m59s.
Total Errors:8.
warp: Cleanup Done
```

Warp analyze showed PUT errors at the timestamps

```
Operation: PUT - total: 7077, 15.0%, Size: 256000000 bytes. Concurrency: 20, Ran 3h0m1s, starting 2024-11-19 00:00:56.946 -0500 EST
Errors: 8
https://<ces-ip>:6443, 2024-11-19 01:03:44 -0500 EST: We encountered an internal error. Please try again.
https://<ces-ip>:6443, 2024-11-19 01:03:44 -0500 EST: We encountered an internal error. Please try again.
https://<ces-ip>:6443, 2024-11-19 01:31:00 -0500 EST: We encountered an internal error. Please try again.
https://<ces-ip>:6443, 2024-11-19 01:42:04 -0500 EST: We encountered an internal error. Please try again.
https://<ces-ip>:6443, 2024-11-19 01:42:04 -0500 EST: We encountered an internal error. Please try again.
https://<ces-ip>:6443, 2024-11-19 02:43:25 -0500 EST: We encountered an internal error. Please try again.
https://<ces-ip>:6443, 2024-11-19 02:52:08 -0500 EST: We encountered an internal error. Please try again.
https://<ces-ip>:6443, 2024-11-19 02:52:08 -0500 EST: We encountered an internal error. Please try again.
 * Throughput: 160.12 MiB/s, 0.66 obj/s

```

output is located here https://ibm.ent.box.com/folder/294550758268

**Comment by rkomandu** [comment]
run started around "Nov 18 23:58:30" , the noobaa file in box are from 00 of Nov 19th, nothing much in the older logs (as such no errors from analyze as well)

**Comment by romayalon** [comment]
@guymguym I talked with @nadavMiz about this bug today, is there a reason we are awaiting for the deletion of the parts? seems to me like this can be done in the background so we won't delay our response.
In addition, Nadav mentioned he saw there is a TODO in the original keep alive implementation on version id response, he can add more details

**Comment by guymguym** [comment]
@romayalon if we don't wait for the deletion of parts we can't delete the multipart directory as well. Why are we waiting for so long anyway? If we want to speed it up then we can create a single fs_napi operation that will delete the entire directory and all the files in it, so we won't have to submit so many work items.

**Comment by nadavMiz** [comment]
@romayalon @guymguym the TODO mentioned is this:
```
    // TODO: Should be refactored when coding the complete solution
    // We need to know all of these things prior to completion
    // This also leaves a gap on long versioned/encrypted uploads (failure to assign headers after responding)
```
looks like the function `http_utils.set_keep_alive_whitespace_interval` sends headers as heartbeat after timeout. this causes the `Cannot set headers after they are sent to the client` error when trying to set version-id in headers

I am not sure why unlink is taking so long, but other operations occasionally take that long as well. for example:
```
[2056231]: 2024-11-19 02:44:48.964316 [PID-2056231/TID-2056252] [L0] FS::FSWorker::Execute: WARNING FileRead _wrap->_path=/ibm/fvt_fs/s3user-17001-dir/newbucket-warp-vers-mup-19nov/)tePSHyK/.versions/7.(8RNMlI6eghWis7E.rnd_mtime-d5pz1qiv6ps0-ino-1dezd _wrap->_fd=19 _pos=8388608 _offset=0 _len=8388608  took too long: 105.5 ms
```

**Comment by romayalon** [comment]
@guymguym Why do we need to wait with sending the response to after the deletion of the directory?

**Comment by romayalon** [comment]
@guymguym Thanks guy that's what I thought, I think we can really improve this flow, maybe also we can await for the rename of the folder and not wait for the unlinks.

**Comment by nadavMiz** [comment]
@guymguym @romayalon even if we won't wait for the unlink, we would still might still take a long time uploading the file itself. it seems to be the reason we have the keepalive mechanism in the first place. we create the version-id before starting to upload the file. maybe we can somehow pass the version-id to the header before uploading the file and deleting the folder, that way we can wait as long as needed

**Comment by romayalon** [comment]
@nadavMiz regardless of the fix of the `http_utils.set_keep_alive_whitespace_interval(res);` we can improve this flow in namespace_fs, can you please check that?

**Comment by rkomandu** [comment]
this seems to occur in the customer system in 4.17.3 build
